import type { ThemeConfig, PaletteConfig } from '@/types/presentation';

export const presentationThemes: ThemeConfig[] = [
  {
    id: 'modern-minimal-light',
    name: 'Modern Minimal',
    description: 'Clean, airy design with soft accents',
    preview: 'linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%)',
    bgColor: 'F8F9FA',
    bgColorAlt: 'FFFFFF',
    titleColor: '1A1A2E',
    bodyColor: '495057',
    accentColor: '6366F1',
    accentColorAlt: '818CF8',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: false,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'modern-dark',
    name: 'Modern Dark',
    description: 'Sleek dark mode with vibrant highlights',
    preview: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    bgColor: '1A1A2E',
    bgColorAlt: '16213E',
    titleColor: 'FFFFFF',
    bodyColor: 'CBD5E1',
    accentColor: '818CF8',
    accentColorAlt: 'A78BFA',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'gradient-premium',
    name: 'Gradient Premium',
    description: 'Rich gradients with modern typography',
    preview: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    bgColor: '1E1B4B',
    bgColorAlt: '312E81',
    titleColor: 'FFFFFF',
    bodyColor: 'C7D2FE',
    accentColor: 'F472B6',
    accentColorAlt: 'FB923C',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 38,
    sectionTitleSize: 34,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'luxury-black-gold',
    name: 'Luxury Black & Gold',
    description: 'Elegant dark theme with gold accents',
    preview: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 100%)',
    bgColor: '0A0A0A',
    bgColorAlt: '1A1A1A',
    titleColor: 'D4AF37',
    bodyColor: 'D4D4D4',
    accentColor: 'D4AF37',
    accentColorAlt: 'F5D060',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: false,
    darkTheme: true,
  },
  {
    id: 'clean-corporate',
    name: 'Clean Corporate',
    description: 'Professional blue-toned business style',
    preview: 'linear-gradient(135deg, #ffffff 0%, #f0f4f8 100%)',
    bgColor: 'FFFFFF',
    bgColorAlt: 'F0F4F8',
    titleColor: '1E3A5F',
    bodyColor: '4A5568',
    accentColor: '2563EB',
    accentColorAlt: '3B82F6',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 26,
    bodyFontSize: 13,
    bulletFontSize: 12,
    coverTitleSize: 34,
    sectionTitleSize: 30,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: false,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'creative-editorial',
    name: 'Creative Editorial',
    description: 'Bold layouts with creative flair',
    preview: 'linear-gradient(135deg, #fdf2f8 0%, #fce7f3 50%, #fbcfe8 100%)',
    bgColor: 'FDF2F8',
    bgColorAlt: 'FFFFFF',
    titleColor: '831843',
    bodyColor: '6B7280',
    accentColor: 'EC4899',
    accentColorAlt: 'F472B6',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 30,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 38,
    sectionTitleSize: 34,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'deep-navy',
    name: 'Deep Navy',
    description: 'Dark navy with teal accents for impactful presentations',
    preview: 'linear-gradient(135deg, #0d1b2a 0%, #1b2838 100%)',
    bgColor: '0D1B2A',
    bgColorAlt: '1B2838',
    titleColor: 'E0F2FE',
    bodyColor: '94A3B8',
    accentColor: '2DD4BF',
    accentColorAlt: '14B8A6',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'bold-gradient-purple',
    name: 'Bold Gradient Purple',
    description: 'Vibrant purple gradients with energetic feel',
    preview: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 50%, #a78bfa 100%)',
    bgColor: '4C1D95',
    bgColorAlt: '5B21B6',
    titleColor: 'FFFFFF',
    bodyColor: 'DDD6FE',
    accentColor: 'F59E0B',
    accentColorAlt: 'FBBF24',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 30,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 38,
    sectionTitleSize: 34,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'editorial-cream',
    name: 'Editorial Cream',
    description: 'Warm cream tones with a refined serif feel',
    preview: 'linear-gradient(135deg, #fefce8 0%, #fef3c7 100%)',
    bgColor: 'FEFCE8',
    bgColorAlt: 'FFFBEB',
    titleColor: '451A03',
    bodyColor: '78716C',
    accentColor: 'B45309',
    accentColorAlt: 'D97706',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: false,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'startup-cyan',
    name: 'Startup Cyan',
    description: 'Bright cyan tech-forward startup style',
    preview: 'linear-gradient(135deg, #ecfeff 0%, #cffafe 50%, #a5f3fc 100%)',
    bgColor: 'ECFEFF',
    bgColorAlt: 'FFFFFF',
    titleColor: '164E63',
    bodyColor: '475569',
    accentColor: '0891B2',
    accentColorAlt: '06B6D4',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'elegant-monochrome',
    name: 'Elegant Monochrome',
    description: 'Sophisticated grayscale with a single accent color',
    preview: 'linear-gradient(135deg, #f5f5f5 0%, #e5e5e5 100%)',
    bgColor: 'F5F5F5',
    bgColorAlt: 'FFFFFF',
    titleColor: '171717',
    bodyColor: '525252',
    accentColor: 'DC2626',
    accentColorAlt: 'EF4444',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: false,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'warm-neutral',
    name: 'Warm Neutral',
    description: 'Warm beige and earth tones for a grounded feel',
    preview: 'linear-gradient(135deg, #faf5ef 0%, #f5ebe0 100%)',
    bgColor: 'FAF5EF',
    bgColorAlt: 'FFFFFF',
    titleColor: '44403C',
    bodyColor: '78716C',
    accentColor: 'C2410C',
    accentColorAlt: 'EA580C',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: false,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'glass-dark',
    name: 'Glass Dark',
    description: 'Glass morphism dark theme with frosted overlays',
    preview: 'linear-gradient(135deg, #111827 0%, #1f2937 50%, #111827 100%)',
    bgColor: '111827',
    bgColorAlt: '1F2937',
    titleColor: 'F9FAFB',
    bodyColor: '9CA3AF',
    accentColor: '60A5FA',
    accentColorAlt: '93C5FD',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'academic-clean',
    name: 'Academic Clean',
    description: 'Clean serif-inspired academic presentation style',
    preview: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)',
    bgColor: 'FFFFFF',
    bgColorAlt: 'F8FAFC',
    titleColor: '1E293B',
    bodyColor: '475569',
    accentColor: '0F766E',
    accentColorAlt: '14B8A6',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 26,
    bodyFontSize: 13,
    bulletFontSize: 12,
    coverTitleSize: 34,
    sectionTitleSize: 30,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: false,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'neon-dark',
    name: 'Neon Dark',
    description: 'Electric neon glow on dark background',
    preview: 'linear-gradient(135deg, #0a0a1a 0%, #1a0a2e 50%, #0a1a2e 100%)',
    bgColor: '0A0A1A',
    bgColorAlt: '12122A',
    titleColor: '00F5FF',
    bodyColor: 'B8C5D6',
    accentColor: 'FF00E5',
    accentColorAlt: '7B2FFF',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 30,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 38,
    sectionTitleSize: 34,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'gradient-ocean',
    name: 'Gradient Ocean',
    description: 'Deep blue ocean gradient with smooth transitions',
    preview: 'linear-gradient(135deg, #0c2d48 0%, #145374 40%, #2e8bc0 100%)',
    bgColor: '0C2D48',
    bgColorAlt: '145374',
    titleColor: 'FFFFFF',
    bodyColor: 'B8D4E3',
    accentColor: '2E8BC0',
    accentColorAlt: '6CB4EE',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'gradient-sunset-fire',
    name: 'Sunset Fire',
    description: 'Warm sunset gradients with orange and red tones',
    preview: 'linear-gradient(135deg, #2d1b1b 0%, #6b2c2c 40%, #c44536 100%)',
    bgColor: '2D1B1B',
    bgColorAlt: '3D2222',
    titleColor: 'FFD6A5',
    bodyColor: 'E8C9B0',
    accentColor: 'FF6B35',
    accentColorAlt: 'FF9F1C',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 30,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 38,
    sectionTitleSize: 34,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'corporate-modern',
    name: 'Corporate Modern',
    description: 'Sharp professional design with bold accent bars',
    preview: 'linear-gradient(135deg, #f7f8fa 0%, #ebedf2 50%, #dfe2e8 100%)',
    bgColor: 'F7F8FA',
    bgColorAlt: 'FFFFFF',
    titleColor: '0B1426',
    bodyColor: '3D4F6F',
    accentColor: '0052CC',
    accentColorAlt: '2684FF',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'bold-geometric',
    name: 'Bold Geometric',
    description: 'Strong geometric shapes with high contrast',
    preview: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 30%, #e94560 100%)',
    bgColor: '1A1A2E',
    bgColorAlt: '16213E',
    titleColor: 'EAEAEA',
    bodyColor: 'A9B4C2',
    accentColor: 'E94560',
    accentColorAlt: 'FF6B6B',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 32,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 40,
    sectionTitleSize: 36,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'pastel-dream',
    name: 'Pastel Dream',
    description: 'Soft pastel gradients with a dreamy aesthetic',
    preview: 'linear-gradient(135deg, #fce4ec 0%, #e1bee7 40%, #bbdefb 100%)',
    bgColor: 'FDF2F8',
    bgColorAlt: 'FFF5F7',
    titleColor: '4A154B',
    bodyColor: '6B5B73',
    accentColor: 'AB47BC',
    accentColorAlt: 'CE93D8',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: false,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'midnight-aurora',
    name: 'Midnight Aurora',
    description: 'Northern lights inspired gradients on dark canvas',
    preview: 'linear-gradient(135deg, #0d1117 0%, #161b22 30%, #238636 60%, #1f6feb 100%)',
    bgColor: '0D1117',
    bgColorAlt: '161B22',
    titleColor: '58A6FF',
    bodyColor: '8B949E',
    accentColor: '238636',
    accentColorAlt: '3FB950',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'gradient-royal',
    name: 'Royal Gradient',
    description: 'Luxurious deep purple to gold gradient',
    preview: 'linear-gradient(135deg, #1a0533 0%, #2d1058 40%, #6b2fa0 70%, #d4af37 100%)',
    bgColor: '1A0533',
    bgColorAlt: '2D1058',
    titleColor: 'F0D060',
    bodyColor: 'C9B3D9',
    accentColor: 'D4AF37',
    accentColorAlt: 'F5D060',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 30,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 38,
    sectionTitleSize: 34,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    description: 'Clean mint green with white for a refreshing look',
    preview: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 40%, #bbf7d0 100%)',
    bgColor: 'F0FDF4',
    bgColorAlt: 'FFFFFF',
    titleColor: '14532D',
    bodyColor: '4B6358',
    accentColor: '16A34A',
    accentColorAlt: '22C55E',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: false,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'carbon-fiber',
    name: 'Carbon Fiber',
    description: 'Ultra-dark with metallic silver accents',
    preview: 'linear-gradient(135deg, #1c1c1c 0%, #2d2d2d 50%, #1c1c1c 100%)',
    bgColor: '1C1C1C',
    bgColorAlt: '2D2D2D',
    titleColor: 'E8E8E8',
    bodyColor: '999999',
    accentColor: '00B4D8',
    accentColorAlt: '48CAE4',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
  {
    id: 'gradient-candy',
    name: 'Candy Gradient',
    description: 'Playful candy-colored gradients with vibrant energy',
    preview: 'linear-gradient(135deg, #ff6b6b 0%, #feca57 30%, #48dbfb 60%, #ff9ff3 100%)',
    bgColor: 'FFF5F5',
    bgColorAlt: 'FFFFFF',
    titleColor: 'CC2936',
    bodyColor: '6B5B73',
    accentColor: 'FF6B6B',
    accentColorAlt: 'FECA57',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 30,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 38,
    sectionTitleSize: 34,
    marginX: 0.8,
    marginY: 0.7,
    shapeAccent: true,
    gradientCover: false,
    darkTheme: false,
  },
  {
    id: 'slate-professional',
    name: 'Slate Professional',
    description: 'Sophisticated slate tones for executive presentations',
    preview: 'linear-gradient(135deg, #1e293b 0%, #334155 50%, #475569 100%)',
    bgColor: '1E293B',
    bgColorAlt: '334155',
    titleColor: 'F1F5F9',
    bodyColor: '94A3B8',
    accentColor: 'F59E0B',
    accentColorAlt: 'FCD34D',
    titleFont: 'Calibri',
    bodyFont: 'Calibri',
    titleFontSize: 28,
    bodyFontSize: 14,
    bulletFontSize: 13,
    coverTitleSize: 36,
    sectionTitleSize: 32,
    marginX: 0.7,
    marginY: 0.6,
    shapeAccent: true,
    gradientCover: true,
    darkTheme: true,
  },
];

export function getTheme(id: string): ThemeConfig {
  return presentationThemes.find(t => t.id === id) || presentationThemes[0];
}

export const presentationPalettes: PaletteConfig[] = [
  {
    id: 'ocean-bold',
    name: 'Ocean Bold',
    primary: '#1E40AF',
    secondary: '#3B82F6',
    accent: '#F59E0B',
    bgLight: '#EFF6FF',
    bgDark: '#1E3A5F',
    gradient: 'linear-gradient(135deg, #1E40AF 0%, #3B82F6 100%)',
  },
  {
    id: 'sunset-warm',
    name: 'Sunset Warm',
    primary: '#DC2626',
    secondary: '#F97316',
    accent: '#FBBF24',
    bgLight: '#FFF7ED',
    bgDark: '#7C2D12',
    gradient: 'linear-gradient(135deg, #DC2626 0%, #F97316 100%)',
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    primary: '#166534',
    secondary: '#22C55E',
    accent: '#A3E635',
    bgLight: '#F0FDF4',
    bgDark: '#14532D',
    gradient: 'linear-gradient(135deg, #166534 0%, #22C55E 100%)',
  },
  {
    id: 'lavender-pastel',
    name: 'Lavender Pastel',
    primary: '#7C3AED',
    secondary: '#A78BFA',
    accent: '#F0ABFC',
    bgLight: '#FAF5FF',
    bgDark: '#4C1D95',
  },
  {
    id: 'midnight-cool',
    name: 'Midnight Cool',
    primary: '#1E293B',
    secondary: '#334155',
    accent: '#38BDF8',
    bgLight: '#F8FAFC',
    bgDark: '#0F172A',
    gradient: 'linear-gradient(135deg, #1E293B 0%, #0F172A 100%)',
  },
  {
    id: 'coral-blush',
    name: 'Coral Blush',
    primary: '#E11D48',
    secondary: '#FB7185',
    accent: '#FDA4AF',
    bgLight: '#FFF1F2',
    bgDark: '#881337',
  },
  {
    id: 'slate-mono',
    name: 'Slate Monochrome',
    primary: '#1E293B',
    secondary: '#64748B',
    accent: '#CBD5E1',
    bgLight: '#F1F5F9',
    bgDark: '#0F172A',
  },
  {
    id: 'teal-gradient',
    name: 'Teal Gradient',
    primary: '#0D9488',
    secondary: '#2DD4BF',
    accent: '#5EEAD4',
    bgLight: '#F0FDFA',
    bgDark: '#134E4A',
    gradient: 'linear-gradient(135deg, #0D9488 0%, #2DD4BF 100%)',
  },
  {
    id: 'gold-neutral',
    name: 'Gold Neutral',
    primary: '#92400E',
    secondary: '#D97706',
    accent: '#FDE68A',
    bgLight: '#FFFBEB',
    bgDark: '#451A03',
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    primary: '#2563EB',
    secondary: '#60A5FA',
    accent: '#E0F2FE',
    bgLight: '#EFF6FF',
    bgDark: '#1E3A8A',
    gradient: 'linear-gradient(135deg, #2563EB 0%, #7C3AED 100%)',
  },
  {
    id: 'rose-warm',
    name: 'Rose Warm',
    primary: '#9F1239',
    secondary: '#FB7185',
    accent: '#FECDD3',
    bgLight: '#FFF1F2',
    bgDark: '#4C0519',
  },
  {
    id: 'charcoal-minimal',
    name: 'Charcoal Minimal',
    primary: '#171717',
    secondary: '#404040',
    accent: '#A3A3A3',
    bgLight: '#FAFAFA',
    bgDark: '#0A0A0A',
  },
];

export function getPalette(id: string): PaletteConfig {
  return presentationPalettes.find(p => p.id === id) || presentationPalettes[0];
}
