export interface TutorialSection {
  id: string;
  title: string;
  icon: string;
  items: TutorialItem[];
}

export interface TutorialItem {
  title: string;
  description: string;
}

export const tutorialSections: TutorialSection[] = [
  {
    id: 'onboarding-demo',
    title: 'Welcome & Demo Data',
    icon: '🚀',
    items: [
      { title: 'Welcome to MindFlow', description: 'MindFlow is your all-in-one companion for productivity, wellness, and learning. We\'ve pre-loaded some demo data to help you explore the features right away!' },
      { title: 'Why Demo Data?', description: 'Demo data (goals, habits, tasks, etc.) shows you how the app looks when it\'s full of life. It helps you understand the charts, streaks, and progress bars immediately.' },
      { title: 'Clear & Start Fresh', description: 'Ready to add your own data? You can clear all demo data anytime from Settings → Data Management. Your study files will always be preserved.' },
      { title: '100% Private', description: 'All your data, including demo data and anything you add, is stored locally on your device. We never see your personal information.' },
    ],
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    icon: '🏠',
    items: [
      { title: 'Overview Cards', description: 'See your daily progress at a glance — habits completed, tasks done, focus time, and active goals all in one place.' },
      { title: 'Quick Actions', description: 'Tap any module card to jump directly into that module. Drag to rearrange, or tap the pencil icon to customize which modules appear.' },
      { title: 'Daily Quote', description: 'A fresh motivational quote appears each day. Tap it to copy or share.' },
      { title: 'Streak Tracker', description: 'Your current app usage streak is shown at the top. Open the app daily to keep it going!' },
      { title: 'Weekly Streak Calendar', description: 'View a 7-day calendar showing which days you were active across all modules.' },
      { title: 'Mood Tracker', description: 'Your latest mood is displayed on the dashboard with a 7-day trend. Tap to go to Wellness.' },
      { title: 'Upcoming Reminders', description: 'See your next 3 upcoming reminders from Tasks and To-Dos right on the dashboard.' },
      { title: 'Recent Activity Feed', description: 'A live feed of your latest actions — swipe to dismiss individual items.' },
    ],
  },
  {
    id: 'goals',
    title: 'Goals',
    icon: '🎯',
    items: [
      { title: 'Create Goals', description: 'Set meaningful goals with a title, description, target date, and category. Break big goals into smaller milestones.' },
      { title: 'Milestones', description: 'Add checkpoints within each goal. Check them off as you make progress — the progress bar updates automatically.' },
      { title: 'Categories & Filters', description: 'Organize goals by category (Health, Career, Personal, etc.) and filter to focus on what matters.' },
      { title: 'Progress Tracking', description: 'Each goal shows a visual progress bar based on completed milestones. Completed goals move to a "Done" section.' },
      { title: 'Global Edit', description: 'Need to change a goal? Tap the edit button to update the title, category, description, deadline, or reminder settings anytime.' },
    ],
  },
  {
    id: 'habits',
    title: 'Habits',
    icon: '🔥',
    items: [
      { title: 'Daily Habits', description: 'Create habits you want to build. Each day, check them off to build your streak.' },
      { title: 'Streaks & XP', description: 'Every consecutive day you complete a habit adds to its streak and earns XP. Level up by staying consistent!' },
      { title: 'Habit Categories', description: 'Organize habits by type: Health, Productivity, Mindfulness, and more.' },
      { title: 'Weekly View & Heatmap', description: 'See which days you completed each habit with the weekly dot grid. Switch to the Heatmap view for a full overview.' },
      { title: 'Quests & Badges', description: 'Complete quests to earn badges. Visit the Rewards Shop to spend XP on unlockables.' },
      { title: 'Edit Quests', description: 'Change of plans? You can edit any habit quest title and frequency (Daily/Weekly) to better suit your changing lifestyle.' },
    ],
  },
  {
    id: 'tasks',
    title: 'Tasks',
    icon: '✅',
    items: [
      { title: 'Task Management', description: 'Create tasks with priority levels (Low, Medium, High, Urgent), due dates, and categories.' },
      { title: 'Priority Colors', description: 'Tasks are color-coded by priority so you can instantly spot what needs attention first.' },
      { title: 'Subtasks', description: 'Break complex tasks into subtasks. The parent task shows progress based on completed subtasks.' },
      { title: 'Filters & Sorting', description: 'Filter by status, priority, or category. Sort by due date, priority, or creation date.' },
      { title: 'Reminders & Alarms', description: 'Set reminder dates and times on tasks. Choose alarm sounds and get notified so you never miss a deadline.' },
      { title: 'Quick Changes', description: 'Use the global edit feature in the task detail view to update priorities, projects, or due dates without recreating the task.' },
    ],
  },
  {
    id: 'focus',
    title: 'Focus Timer',
    icon: '⏱️',
    items: [
      { title: 'Pomodoro Timer', description: 'Work in focused sessions (default 25 min) followed by short breaks (5 min). After 4 sessions, take a longer break.' },
      { title: 'Custom Durations', description: 'Adjust work, short break, and long break durations to match your flow.' },
      { title: 'Session Tracking', description: 'Every completed session is logged. View your total focus time in Analytics.' },
      { title: 'Ambient Sounds', description: 'Play background sounds (rain, ocean, forest) while focusing to help you concentrate.' },
      { title: 'Audio Visualizer', description: 'Watch a real-time audio visualizer while ambient sounds play for an immersive focus experience.' },
    ],
  },
  {
    id: 'notes',
    title: 'Notes',
    icon: '📝',
    items: [
      { title: 'Quick Notes', description: 'Capture thoughts instantly. Notes support rich text with markdown-style formatting.' },
      { title: 'Folders & Tags', description: 'Organize notes in nested folders and add tags for flexible categorization.' },
      { title: 'Version History', description: 'Every save creates a version. Restore any previous state of a note from its version history.' },
      { title: 'Knowledge Graph', description: 'Visualize connections between notes in an interactive knowledge graph view.' },
      { title: 'Pin & Search', description: 'Pin important notes to the top. Use search to find notes by title or content instantly.' },
      { title: 'Smart Scheduling', description: 'Add reminders, schedules, and alarms to any note. Use the edit button to update these settings whenever needed.' },
    ],
  },
  {
    id: 'books',
    title: 'Books & Reading',
    icon: '📚',
    items: [
      { title: 'Built-in Library', description: 'MindFlow comes with 9 pre-loaded books you can read directly in the app.' },
      { title: 'Upload Your Books', description: 'Add your own PDF, TXT, or EPUB files (up to 150MB). They\'re stored locally via IndexedDB.' },
      { title: 'Reading Progress', description: 'The app remembers your reading position. Jump back in right where you left off.' },
      { title: 'Theme Support', description: 'The reader supports adjustable themes — read comfortably in light, dark, or AMOLED mode.' },
      { title: 'Swipe Navigation', description: 'On mobile, swipe left/right to turn pages for a natural reading experience.' },
      { title: 'AI Summary & Explainer', description: 'Use AI to generate summaries or simplified explanations of any book. Choose Quick Summary, Deep Dive, or ELI5 mode.' },
      { title: 'In-App Note Taking', description: 'Take notes directly while reading your books. Tap the notes icon in the header to open the split-screen notes panel.' },
      { title: 'Saved Notes & Summaries', description: 'Access all your saved notes and AI summaries for each book in an expandable section. View them directly in the app or download as TXT.' },
      { title: 'Auto-Rotate', description: 'Tap the rotate icon in the reader header to switch between portrait and landscape modes on mobile.' },
      { title: 'Footer Visibility', description: 'Toggle the bottom page controls and brightness slider for a distraction-free, immersive reading experience.' },
      { title: 'Reader Settings', description: 'Customize brightness, dark mode, and zoom level for a perfect reading experience. Reset zoom anytime with a single tap.' },
      { title: 'Bookmarks & Notes', description: 'Save your place and capture important thoughts. Access all your bookmarks from the list view or view saved notes per book.' },
    ],
  },
  {
    id: 'todos',
    title: 'To-Do List',
    icon: '📋',
    items: [
      { title: 'Quick Add', description: 'A lightweight to-do list for quick tasks. Tap the input, type, and hit enter — done.' },
      { title: 'Check Off', description: 'Tap the checkbox to mark items complete. Completed items move to the bottom.' },
      { title: 'Reminders', description: 'Set reminder dates and times with custom alarms on individual to-do items.' },
      { title: 'Delete & Clear', description: 'Swipe or tap the delete icon to remove items. Use "Clear completed" to clean up.' },
      { title: 'Edit To-Dos', description: 'Tap any to-do to edit its text, priority, or reminder settings directly.' },
    ],
  },
  {
    id: 'study',
    title: 'Study Planner (LMS)',
    icon: '🎓',
    items: [
      { title: 'Study Sessions', description: 'Create sessions with subject, topic, duration, category (School, University, Self-study, etc.), and scheduled date/time.' },
      { title: 'Import Materials', description: 'Import PDF, TXT, EPUB, PPTX/PPT files or MP4/WebM videos directly into a session for split-screen study.' },
      { title: 'High-Fidelity Slides', description: 'PPTX/PPT files render with an OOXML-based engine preserving original layouts, fonts, and formatting.' },
      { title: 'Video Player', description: 'Watch imported lecture videos with full playback controls — play, pause, seek, fullscreen, and volume.' },
      { title: 'Split-Screen Notes', description: 'Take notes side-by-side while reading documents or watching videos. Notes auto-save every 10 seconds with .txt export.' },
      { title: 'Multi-Color Highlighting', description: 'Highlight text in your study materials with multiple color options. Highlights persist across sessions.' },
      { title: 'Advanced Zoom', description: 'Zoom from 0.5x to 5x using pinch-to-zoom, mouse wheel, or manual buttons. Toggle landscape mode on mobile.' },
      { title: 'Study Timer', description: 'Start a per-session timer with customizable alarm sounds. A mini stopwatch overlay tracks time while you multitask.' },
      { title: 'Study Dashboard', description: 'Toggle the dashboard to see total study time, materials count, subject-time charts, category pie chart, and 14-day trends.' },
      { title: 'Study Quizzes', description: 'Generate AI-powered quizzes from your study materials. Review quiz history and track your scores over time.' },
      { title: 'Mark Complete', description: 'Tap the green checkmark to mark materials as completed. Track your progress across all imported materials.' },
      { title: 'Study History', description: 'View logged study sessions with subject, topic, and duration. Delete entries individually — stats update in real-time.' },
      { title: 'Session Editing', description: 'Update study session details like subject, topic, or scheduled time using the global edit button.' },
      { title: 'Material Annotations', description: 'Take notes while studying. Your notes are saved per material and can be accessed across sessions.' },
    ],
  },
  {
    id: 'studybuddy',
    title: 'Kira Study Buddy',
    icon: '✨',
    items: [
      { title: 'AI Homework Help', description: 'Kira Study Buddy is your dedicated academic AI assistant — ask any question about math, science, history, or any subject.' },
      { title: 'Step-by-Step Solutions', description: 'Get detailed step-by-step breakdowns of problems with clear explanations and formulas.' },
      { title: 'Image & Screenshot Support', description: 'Attach photos or screenshots (up to 5MB) of homework problems, textbook pages, or handwritten notes for AI analysis.' },
      { title: 'Material Context', description: 'When opened inside a study reader, Kira Study Buddy automatically knows which material and page you\'re on for contextual help.' },
      { title: 'Persistent Chat', description: 'Your conversation history is saved locally, so you can close and reopen without losing your chat.' },
      { title: 'Access Anywhere in Study', description: 'Available as a floating button on the Study Planner page and inside every document/video reader.' },
    ],
  },
  {
    id: 'expenses',
    title: 'Expenses & Budgeting',
    icon: '💰',
    items: [
      { title: 'Log Expenses', description: 'Record spending with amount, category (Food, Transport, Entertainment, Shopping, Bills), and title.' },
      { title: 'Monthly Income', description: 'Set your monthly income to see a dynamic donut chart of income vs. expenditure — turns red when over budget.' },
      { title: 'Budget Limits', description: 'Set per-category budget limits with visual progress bars. Get toast alerts at 80% and when exceeded.' },
      { title: 'Monthly Trends', description: 'View a 6-month trends chart with income vs. expenses and a savings trend line. Edit historical income values.' },
      { title: 'Savings Tracker', description: 'See real-time savings (or overspend) with percentage indicators.' },
      { title: 'Reports', description: 'Download detailed reports (TXT/CSV) with category breakdowns and custom date filtering.' },
    ],
  },
  {
    id: 'timetracking',
    title: 'Time Tracking',
    icon: '⏰',
    items: [
      { title: 'Track Time', description: 'Log time spent on activities. See where your hours go each day.' },
      { title: 'Categories', description: 'Organize time entries by project or category for productivity insights.' },
      { title: 'Daily & Weekly Views', description: 'Review your time logs by day or week to understand your patterns.' },
      { title: 'Edit Entries', description: 'Made a mistake? You can edit activity names, durations, projects, and billable status for any past entry.' },
      { title: 'Project Management', description: 'Edit your projects and hourly rates. Changes will automatically update all associated billing calculations.' },
    ],
  },
  {
    id: 'wellness',
    title: 'Wellness',
    icon: '💚',
    items: [
      { title: 'Mood Tracking', description: 'Log your mood throughout the day. See patterns over time to understand your emotional health.' },
      { title: 'Meditation Timer', description: 'Guided and unguided meditation sessions with ambient sounds and customizable duration.' },
      { title: 'OCD Support Tools', description: 'ERP (Exposure & Response Prevention) exercises, anxiety tracking, and coping strategies — designed with care.' },
      { title: 'Grounding Exercises', description: 'Access 5-4-3-2-1 grounding and breathing exercises anytime via the floating green button on every page.' },
      { title: 'Sleep Tracking', description: 'Log your sleep hours and quality. See trends alongside mood for a holistic wellness view.' },
      { title: 'Water Intake', description: 'Track daily water intake with reminders every 2 hours to stay hydrated.' },
      { title: 'Wellness Records', description: 'Your routines and reassurance journal entries can be edited anytime via the edit button to reflect your latest insights and feelings.' },
    ],
  },
  {
    id: 'reminders',
    title: 'Reminders',
    icon: '🔔',
    items: [
      { title: 'Custom Reminders', description: 'Set one-time or recurring reminders with custom messages and times.' },
      { title: 'Smart Notifications', description: 'Get notified for habits, focus sessions, water intake, study sessions, and more — all configurable in Settings.' },
      { title: 'Notification History', description: 'Every notification is logged. View past notifications in Settings → History.' },
      { title: 'Alarm Sounds', description: 'Choose from multiple alarm sounds (Bells, Chime, Nature, Urgent) for each reminder.' },
    ],
  },
  {
    id: 'analytics',
    title: 'Analytics',
    icon: '📊',
    items: [
      { title: 'Productivity Score', description: 'A daily score based on tasks completed, habits maintained, and focus time logged.' },
      { title: 'Charts & Trends', description: 'Visual charts showing progress across all modules including a dedicated Study tab with subject-time breakdown.' },
      { title: 'AI Report', description: 'Generate an AI-powered report with personalized recommendations. Academic users (School/University) get tailored study feedback including quiz performance.' },
      { title: 'Wellness Score', description: 'Track your mental wellness trends alongside productivity for a balanced view.' },
      { title: 'Study Analytics', description: 'The Study tab shows minutes per subject in a bar chart, material completion rates, and quiz score trends.' },
      { title: 'Quiz Performance', description: 'View quiz scores and trends in the AI Analytics report. Your quiz history feeds into personalized academic feedback.' },
    ],
  },
  {
    id: 'chat',
    title: 'Kira (Wellness Buddy)',
    icon: '🌟',
    items: [
      { title: 'Chat with Kira', description: 'Kira is your personal wellness buddy — not a therapist, but a real friend who listens, celebrates, and helps.' },
      { title: 'Quick Prompts', description: 'Use the suggested prompts to start a conversation, or just type whatever\'s on your mind.' },
      { title: 'Text-to-Speech', description: 'Tap the speaker icon on any Kira message to hear it read aloud.' },
      { title: 'Floating Button', description: 'Tap the Kira bubble on any page to quickly open the chat without navigating away.' },
      { title: 'Mood Check-in', description: 'Share your mood from the Kira greeting popup — it auto-sends to the chat for a personalized response.' },
    ],
  },
  {
    id: 'emergency',
    title: 'Emergency Contacts',
    icon: '🛡️',
    items: [
      { title: 'Safety Protocol', description: 'Enable the safety protocol in Settings to automatically alert emergency contacts if you\'re inactive for a set number of days.' },
      { title: 'Add Contacts', description: 'Add up to 5 emergency contacts with name, phone number, and relationship.' },
      { title: 'Inactivity Timer', description: 'Set the inactivity threshold (1-30 days). If you don\'t open the app within that window, contacts are alerted.' },
    ],
  },
  {
    id: 'presentation-generator',
    title: 'Presentation Maker',
    icon: '📊',
    items: [
      { title: 'AI Generation', description: 'Create professional presentations by entering a topic — AI generates slides with titles, content, and speaker notes automatically.' },
      { title: 'PDF/DOCX Upload', description: 'Upload a PDF or DOCX file and let AI extract key points to build a full presentation from your existing documents.' },
      { title: 'Text Input', description: 'Paste or type raw text and AI will structure it into organized slides with proper headings and bullet points.' },
      { title: 'Slide Editor', description: 'Edit individual slides after generation — modify titles, content, speaker notes, and reorder slides with drag-and-drop.' },
      { title: 'Themes', description: 'Choose from multiple professional themes to style your presentation. Switch themes anytime and preview changes instantly.' },
      { title: 'PPTX Export', description: 'Download your finished presentation as a PowerPoint (.pptx) file ready for use in Microsoft PowerPoint, Google Slides, or Keynote.' },
      { title: 'Speaker Notes', description: 'Each slide includes AI-generated speaker notes to guide your delivery. Edit them to add your own talking points.' },
      { title: 'Study Planner Integration', description: 'Presentations created here can be linked to study sessions in the Study Planner for seamless academic workflows.' },
    ],
  },
  {
    id: 'presentation-coach',
    title: 'Presentation Coach',
    icon: '🎤',
    items: [
      { title: 'Real-Time Coaching', description: 'Practice your presentation with live AI feedback on delivery, pacing, filler words, and body language as you speak.' },
      { title: 'Camera + Mic Analysis', description: 'Enable your camera and microphone for full analysis — the coach evaluates both your speech patterns and visual presence.' },
      { title: '7 Scoring Categories', description: 'Get scored across 7 categories: Clarity, Pace, Filler Words, Eye Contact, Gestures, Vocal Variety, and Structure.' },
      { title: 'Live Feedback', description: 'Receive real-time tips and suggestions while presenting — the coach flags issues as they happen so you can adjust immediately.' },
      { title: 'Teleprompter', description: 'Use the built-in teleprompter to display your script while practicing. Adjust scroll speed and font size for comfortable reading.' },
      { title: 'Question Mode', description: 'Practice handling Q&A — the AI generates relevant questions based on your topic for you to answer on the spot.' },
      { title: 'Script Generation', description: 'Generate a full presentation script from your topic using AI. Use it as a starting point or load it into the teleprompter.' },
      { title: 'Reports', description: 'After each session, get a detailed performance report with scores, strengths, areas for improvement, and actionable tips.' },
      { title: 'Session History', description: 'Review past coaching sessions and track your improvement over time with score trends and session comparisons.' },
    ],
  },
  {
    id: 'weather',
    title: 'Weather Module',
    icon: '🌤️',
    items: [
      { title: 'Current Weather', description: 'View real-time weather conditions including temperature, humidity, wind speed, and a descriptive summary for any location.' },
      { title: 'Hourly Forecast', description: 'See hour-by-hour weather predictions for the next 24-48 hours with temperature trends and precipitation chances.' },
      { title: 'Daily & 7-Day Forecast', description: 'Plan ahead with daily forecasts showing high/low temperatures, weather conditions, and precipitation probability for the week.' },
      { title: 'Historical Lookup', description: 'Look up past weather data for any date and location to review historical conditions and trends.' },
      { title: 'Location Search', description: 'Search for any city or location worldwide to check its weather. Save favorite locations for quick access.' },
      { title: 'Temperature Units', description: 'Toggle between Celsius and Fahrenheit with a single tap. Your preference is saved and applied everywhere.' },
      { title: 'Dashboard Chip', description: 'A quick weather summary chip appears on the main dashboard showing current conditions at a glance.' },
    ],
  },
  {
    id: 'nutrition',
    title: 'Nutrition Planner',
    icon: '🍽️',
    items: [
      { title: 'Food Logging', description: 'Search 210+ foods by name or alias. Log meals with quantity, unit, and meal type. See instant calorie and macro breakdown.' },
      { title: 'Ingredient Pantry', description: 'Add ingredients you have at home. Categorize them and use them to find matching recipes.' },
      { title: 'Recipe Browser', description: 'Browse 65+ recipes across Bangladeshi, Indian, Chinese, Thai, Korean, Japanese, and Western cuisines. View health scores, ingredients, and step-by-step instructions.' },
      { title: 'Pantry Matching', description: 'Switch to "Match Pantry" mode to find recipes based on ingredients you already have. See match percentage and missing items.' },
      { title: 'Meal Planner', description: 'Generate daily, weekly, or monthly meal plans. Set your cuisine preference and calorie goal. Save and revisit plans anytime.' },
      { title: 'Nutrition Reports', description: 'Generate weekly or monthly reports with health scores, daily averages, meal breakdowns, insights, and recommendations.' },
      { title: 'Health Scoring', description: 'Every meal, recipe, and day gets a health score (green/yellow/red) based on calories, protein, fiber, and fat balance.' },
    ],
  },
  {
    id: 'fitness',
    title: 'Body & Fitness',
    icon: '💪',
    items: [
      { title: 'BMI Calculator', description: 'Enter your weight, height, age, and gender. See your BMI category (underweight/normal/overweight/obese) with color-coded indicator and health insights.' },
      { title: 'Fitness Profile', description: 'Set your fitness goal (lose weight, build muscle, stay fit, flexibility, general fitness). Your profile is saved and used across workout generation.' },
      { title: 'Workout Planner', description: 'Generate workout routines for weekly, monthly, or custom periods. Choose how many sessions per day (1-4) and preferred times (morning/afternoon/evening/night).' },
      { title: 'Smart Routines', description: 'Routines are tailored to your BMI category, gender, and fitness goals. Rest days are automatically scheduled for recovery.' },
      { title: 'Exercise Library', description: 'Browse 50+ exercises across warmup, cardio, strength, HIIT, yoga, flexibility, balance, and cooldown categories. Each with detailed steps and pose visuals.' },
      { title: 'Exercise Swap', description: 'Find an exercise too difficult? Swap it out for a similar one targeting the same muscle groups and difficulty level.' },
      { title: 'Workout Timer', description: 'Use the countdown timer for timed exercises or the stopwatch for free workouts. Get motivational coach messages during your session.' },
      { title: 'Motivational Coach', description: 'An encouraging (slightly intense) fitness coach gives you motivational messages throughout your workout — from warm-up to cool-down.' },
      { title: 'Workout History', description: 'Track completed workouts with duration, calories burned, and exercises performed. Build streaks for consistency.' },
    ],
  },
  {
    id: 'news',
    title: 'News Portal',
    icon: '📰',
    items: [
      { title: 'International & National', description: 'Switch between international news (BBC, Reuters, CNN, Al Jazeera, The Guardian, NPR) and Bangladeshi news (Daily Star, Prothom Alo, Dhaka Tribune, bdnews24).' },
      { title: 'Category Filters', description: 'Filter by Top, World, Politics, Business, Technology, Sports, Entertainment, and Health categories.' },
      { title: 'News Cards', description: 'Each headline shows the source, publication time, thumbnail image, and a summary snippet. Tap to read more.' },
      { title: 'Article View', description: 'See the full headline, image, and summary. Open the full article in your browser with one tap.' },
      { title: 'Search Headlines', description: 'Search across all loaded headlines by title, source, or summary text.' },
      { title: 'Save & Bookmark', description: 'Bookmark articles to read later. Access your saved articles from the bookmark icon.' },
      { title: 'Breaking News', description: 'Articles published within the last hour get a "BREAKING" badge so you never miss urgent news.' },
      { title: 'Offline Fallback', description: 'News is cached locally. If you lose connection, the last loaded news is shown automatically.' },
      { title: 'Pull to Refresh', description: 'Swipe down on the news feed to refresh, or tap the refresh button for the latest headlines.' },
    ],
  },
  {
    id: 'media-library',
    title: 'Media Library',
    icon: '🎵',
    items: [
      { title: 'What is the Media Library?', description: 'The Media Library is your central hub for all AI-generated audio summaries, podcast episodes, and slideshow videos created across every module.' },
      { title: 'Accessing Media Library', description: 'Open it from the Modules page or the Media Library tile. It shows all generated media organized by source — Books, Notes, Study, Presentations, Audio Studio, and Video Studio.' },
      { title: 'Filtering by Source', description: 'Tap the filter buttons at the top (All, Books, Notes, Study, etc.) to see media from a specific module.' },
      { title: 'Playing Media', description: 'Tap any item to expand its player. Audio plays inline. Video slideshows play with animated scenes. Both can be downloaded.' },
      { title: 'Deleting Items', description: 'Tap the trash icon on any item to delete it. Use "Clear All" to remove everything from a particular source module.' },
      { title: 'Storage Note', description: 'Media is stored in your browser\'s IndexedDB, so it persists between sessions. Items won\'t be cleared by a normal app data reset — only by explicitly deleting them.' },
    ],
  },
  {
    id: 'audio-studio',
    title: 'Audio Studio',
    icon: '🎧',
    items: [
      { title: 'What is Audio Studio?', description: 'Audio Studio is a standalone page where you can create AI-narrated audio content from any text — without attaching it to a specific study material or book.' },
      { title: 'Three Input Modes', description: 'Upload a PDF/TXT/MD file, paste text directly, or use the Describe mode to tell Kira what you want — she\'ll write the full script for you!' },
      { title: 'Describe Mode', description: 'Type something like "A 5-minute audio summary about photosynthesis for high school students" and tap Generate Script with AI. Kira will write a complete, well-structured audio script for you.' },
      { title: 'Generation Modes', description: 'Once you have a source, choose from Summary, Explainer, Podcast, or Video modes. Each creates a different style of content using Web Speech API (no internet required for playback).' },
      { title: 'Download & Share', description: 'All generated audio and video is saved locally. You can download it as a WebM file and share it however you like.' },
      { title: 'Media Library Link', description: 'Everything you create in Audio Studio appears in the Media Library under the "Audio Studio" filter. Access your full collection from there.' },
    ],
  },
  {
    id: 'video-studio',
    title: 'Video Studio',
    icon: '🎬',
    items: [
      { title: 'What is Video Studio?', description: 'Video Studio turns text content into animated slideshow videos — scene by scene, with Canvas-rendered animations and narration. Everything runs 100% in your browser.' },
      { title: 'Three Input Modes', description: 'Upload a PDF/TXT/MD file, paste text directly, or use the Describe mode. In Describe mode, Kira structures your content into a scene-by-scene video script.' },
      { title: 'AI Script Generation', description: 'Describe your video concept (e.g., "An intro video for a startup selling eco-friendly packaging") and Kira writes a structured, scene-based script that\'s optimized for visual presentation.' },
      { title: 'How Video is Generated', description: 'The Canvas API splits your content into slides/scenes, renders animated text and visuals, and MediaRecorder captures everything as a WebM video file — no servers, no uploads.' },
      { title: 'Ideal Use Cases', description: 'Perfect for study summaries, explainer content, project intros, presentation rehearsals, or creating educational videos from your study materials.' },
      { title: 'Quality Tip', description: 'For best results, use well-structured text with clear headings or paragraph breaks. Kira\'s AI script generation is designed to create content optimized for visual scenes.' },
    ],
  },
  {
    id: 'settings',
    title: 'Settings & Extras',
    icon: '⚙️',
    items: [
      { title: 'Profile', description: 'Set your name, age, occupation, and avatar. Upload a profile picture or pick an emoji.' },
      { title: 'Themes & Colors', description: 'Switch between Light, Dark, AMOLED, and System themes. Pick from 8 accent colors to match your style.' },
      { title: 'Safety Protocol', description: 'Set up emergency contacts who get alerted if you\'re inactive for a set number of days.' },
      { title: 'Data Management', description: 'Export your data as JSON backup, import from a backup, or clear everything to start fresh. Study files persist in IndexedDB.' },
      { title: 'Accessibility', description: 'Adjust font size (S/M/L/XL), enable high contrast, reduce motion, bold text, and toggle splash sound.' },
      { title: 'Music Player', description: 'Play ambient sounds or motivational tracks. Set a default track, volume, and autoplay. The mini player floats on every page.' },
      { title: 'Symmetry & Order Mode', description: 'Enable strict alignment and uniform spacing throughout the app — designed for OCD comfort.' },
      { title: 'Install as PWA', description: 'Add MindFlow to your home screen for a native app experience with offline support.' },
      { title: 'Notification Settings', description: 'Configure habit, focus, study, quote, weekly summary, and water reminders with custom times.' },
    ],
  },
];
