import { NewsSource } from '@/types/news';

export const NEWS_SOURCES: NewsSource[] = [
  {
    name: 'Reuters',
    feedUrl: 'https://feeds.reuters.com/reuters/topNews',
    mode: 'international',
    category: 'top',
    language: 'en',
    region: 'global',
  },
  {
    name: 'Reuters World',
    feedUrl: 'https://feeds.reuters.com/Reuters/worldNews',
    mode: 'international',
    category: 'world',
    language: 'en',
    region: 'global',
  },
  {
    name: 'Reuters Business',
    feedUrl: 'https://feeds.reuters.com/reuters/businessNews',
    mode: 'international',
    category: 'business',
    language: 'en',
    region: 'global',
  },
  {
    name: 'Reuters Technology',
    feedUrl: 'https://feeds.reuters.com/reuters/technologyNews',
    mode: 'international',
    category: 'technology',
    language: 'en',
    region: 'global',
  },
  {
    name: 'Reuters Sports',
    feedUrl: 'https://feeds.reuters.com/reuters/sportsNews',
    mode: 'international',
    category: 'sports',
    language: 'en',
    region: 'global',
  },
  {
    name: 'Reuters Health',
    feedUrl: 'https://feeds.reuters.com/reuters/healthNews',
    mode: 'international',
    category: 'health',
    language: 'en',
    region: 'global',
  },
  {
    name: 'Reuters Entertainment',
    feedUrl: 'https://feeds.reuters.com/reuters/entertainment',
    mode: 'international',
    category: 'entertainment',
    language: 'en',
    region: 'global',
  },
  {
    name: 'Al Jazeera',
    feedUrl: 'https://www.aljazeera.com/xml/rss/all.xml',
    mode: 'international',
    category: 'world',
    language: 'en',
    region: 'global',
  },
  {
    name: 'BBC World',
    feedUrl: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    mode: 'international',
    category: 'world',
    language: 'en',
    region: 'global',
  },
  {
    name: 'BBC Top',
    feedUrl: 'https://feeds.bbci.co.uk/news/rss.xml',
    mode: 'international',
    category: 'top',
    language: 'en',
    region: 'global',
  },
  {
    name: 'BBC Technology',
    feedUrl: 'https://feeds.bbci.co.uk/news/technology/rss.xml',
    mode: 'international',
    category: 'technology',
    language: 'en',
    region: 'global',
  },
  {
    name: 'BBC Business',
    feedUrl: 'https://feeds.bbci.co.uk/news/business/rss.xml',
    mode: 'international',
    category: 'business',
    language: 'en',
    region: 'global',
  },
  {
    name: 'BBC Sports',
    feedUrl: 'https://feeds.bbci.co.uk/sport/rss.xml',
    mode: 'international',
    category: 'sports',
    language: 'en',
    region: 'global',
  },
  {
    name: 'BBC Entertainment',
    feedUrl: 'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml',
    mode: 'international',
    category: 'entertainment',
    language: 'en',
    region: 'global',
  },
  {
    name: 'BBC Health',
    feedUrl: 'https://feeds.bbci.co.uk/news/health/rss.xml',
    mode: 'international',
    category: 'health',
    language: 'en',
    region: 'global',
  },
  {
    name: 'CNN Top',
    feedUrl: 'http://rss.cnn.com/rss/edition.rss',
    mode: 'international',
    category: 'top',
    language: 'en',
    region: 'global',
  },
  {
    name: 'CNN World',
    feedUrl: 'http://rss.cnn.com/rss/edition_world.rss',
    mode: 'international',
    category: 'world',
    language: 'en',
    region: 'global',
  },
  {
    name: 'CNN Technology',
    feedUrl: 'http://rss.cnn.com/rss/edition_technology.rss',
    mode: 'international',
    category: 'technology',
    language: 'en',
    region: 'global',
  },
  {
    name: 'CNN Entertainment',
    feedUrl: 'http://rss.cnn.com/rss/edition_entertainment.rss',
    mode: 'international',
    category: 'entertainment',
    language: 'en',
    region: 'global',
  },
  {
    name: 'CNN Sports',
    feedUrl: 'http://rss.cnn.com/rss/edition_sport.rss',
    mode: 'international',
    category: 'sports',
    language: 'en',
    region: 'global',
  },
  {
    name: 'The Guardian World',
    feedUrl: 'https://www.theguardian.com/world/rss',
    mode: 'international',
    category: 'world',
    language: 'en',
    region: 'global',
  },
  {
    name: 'The Guardian Politics',
    feedUrl: 'https://www.theguardian.com/politics/rss',
    mode: 'international',
    category: 'politics',
    language: 'en',
    region: 'global',
  },
  {
    name: 'The Guardian Technology',
    feedUrl: 'https://www.theguardian.com/uk/technology/rss',
    mode: 'international',
    category: 'technology',
    language: 'en',
    region: 'global',
  },
  {
    name: 'NPR News',
    feedUrl: 'https://feeds.npr.org/1001/rss.xml',
    mode: 'international',
    category: 'top',
    language: 'en',
    region: 'global',
  },
  {
    name: 'NPR Politics',
    feedUrl: 'https://feeds.npr.org/1014/rss.xml',
    mode: 'international',
    category: 'politics',
    language: 'en',
    region: 'global',
  },

  {
    name: 'The Daily Star Home',
    feedUrl: 'https://www.thedailystar.net/frontpage/rss.xml',
    mode: 'national',
    category: 'top',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Daily Star World',
    feedUrl: 'https://www.thedailystar.net/news/world/rss.xml',
    mode: 'national',
    category: 'world',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Daily Star Business',
    feedUrl: 'https://www.thedailystar.net/business/rss.xml',
    mode: 'national',
    category: 'business',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Daily Star Sports',
    feedUrl: 'https://www.thedailystar.net/sports/rss.xml',
    mode: 'national',
    category: 'sports',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Daily Star Tech',
    feedUrl: 'https://www.thedailystar.net/tech-startup/rss.xml',
    mode: 'national',
    category: 'technology',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Daily Star Entertainment',
    feedUrl: 'https://www.thedailystar.net/entertainment/rss.xml',
    mode: 'national',
    category: 'entertainment',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Prothom Alo Home',
    feedUrl: 'https://en.prothomalo.com/feed',
    mode: 'national',
    category: 'top',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Dhaka Tribune Home',
    feedUrl: 'https://www.dhakatribune.com/rss.xml',
    mode: 'national',
    category: 'top',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Business Standard Home',
    feedUrl: 'https://www.tbsnews.net/rss.xml',
    mode: 'national',
    category: 'top',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Dhaka Tribune Politics',
    feedUrl: 'https://www.dhakatribune.com/articles/politics/rss.xml',
    mode: 'national',
    category: 'politics',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Dhaka Tribune Business',
    feedUrl: 'https://www.dhakatribune.com/articles/business/rss.xml',
    mode: 'national',
    category: 'business',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Dhaka Tribune World',
    feedUrl: 'https://www.dhakatribune.com/articles/world/rss.xml',
    mode: 'national',
    category: 'world',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Dhaka Tribune Tech',
    feedUrl: 'https://www.dhakatribune.com/articles/technology/rss.xml',
    mode: 'national',
    category: 'technology',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Dhaka Tribune Sports',
    feedUrl: 'https://www.dhakatribune.com/articles/sport/rss.xml',
    mode: 'national',
    category: 'sports',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Prothom Alo Politics',
    feedUrl: 'https://en.prothomalo.com/feed/politics',
    mode: 'national',
    category: 'politics',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Prothom Alo Business',
    feedUrl: 'https://en.prothomalo.com/feed/business',
    mode: 'national',
    category: 'business',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'Prothom Alo Sports',
    feedUrl: 'https://en.prothomalo.com/feed/sports',
    mode: 'national',
    category: 'sports',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Business Standard Politics',
    feedUrl: 'https://www.tbsnews.net/bangladesh/politics/rss.xml',
    mode: 'national',
    category: 'politics',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Business Standard Business',
    feedUrl: 'https://www.tbsnews.net/business/rss.xml',
    mode: 'national',
    category: 'business',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Financial Express Politics',
    feedUrl: 'https://thefinancialexpress.com.bd/feed/politics',
    mode: 'national',
    category: 'politics',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'The Financial Express Business',
    feedUrl: 'https://thefinancialexpress.com.bd/feed/business',
    mode: 'national',
    category: 'business',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'New Age Bangladesh',
    feedUrl: 'https://www.newagebd.net/rss.xml',
    mode: 'national',
    category: 'top',
    language: 'en',
    region: 'bangladesh',
  },
  {
    name: 'bdnews24 Bangladesh',
    feedUrl: 'https://bdnews24.com/feed',
    mode: 'national',
    category: 'top',
    language: 'en',
    region: 'bangladesh',
  },
];

export const NEWS_CATEGORIES: { value: string; label: string; modes: string[] }[] = [
  { value: 'top', label: 'Top', modes: ['international', 'national'] },
  { value: 'politics', label: 'Politics', modes: ['international', 'national'] },
  { value: 'world', label: 'World', modes: ['international', 'national'] },
  { value: 'business', label: 'Business', modes: ['international', 'national'] },
  { value: 'technology', label: 'Technology', modes: ['international', 'national'] },
  { value: 'sports', label: 'Sports', modes: ['international', 'national'] },
  { value: 'entertainment', label: 'Entertainment', modes: ['international', 'national'] },
  { value: 'health', label: 'Health', modes: ['international'] },
];
