import type { Exercise } from '@/types/fitness';

export const EXERCISE_DATABASE: Exercise[] = [
  {
    id: 'ex_jumping_jacks',
    name: 'Jumping Jacks',
    emoji: '⭐',
    category: 'warmup',
    muscleGroups: ['full_body', 'cardio_system'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 1,
    reps: 30,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 8,
    steps: [
      { step: 1, instruction: 'Stand upright with feet together and arms at your sides', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Jump and spread your legs wide while raising arms overhead', poseKey: 'jumping_jack_open' },
      { step: 3, instruction: 'Jump back to starting position with feet together and arms down', poseKey: 'standing_neutral' },
      { step: 4, instruction: 'Repeat at a steady rhythm — keep your core tight', poseKey: 'jumping_jack_open' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['lose_weight', 'maintain', 'general_fitness', 'gain_muscle', 'improve_flexibility'] },
    tips: ['Land softly on the balls of your feet', 'Keep a consistent pace', 'Breathe rhythmically'],
    tags: ['warmup', 'cardio', 'full-body', 'beginner'],
  },
  {
    id: 'ex_high_knees',
    name: 'High Knees',
    emoji: '🦵',
    category: 'warmup',
    muscleGroups: ['quads', 'hip_flexors', 'cardio_system'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 1,
    reps: 40,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 10,
    steps: [
      { step: 1, instruction: 'Stand with feet hip-width apart, arms at sides', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Drive right knee up toward chest as high as possible', poseKey: 'high_knee_right' },
      { step: 3, instruction: 'Quickly switch and drive left knee up while right foot lands', poseKey: 'high_knee_left' },
      { step: 4, instruction: 'Pump your arms in sync — opposite arm to knee', poseKey: 'high_knee_right' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'maintain', 'general_fitness'] },
    tips: ['Stay on the balls of your feet', 'Keep your core engaged', 'Drive knees as high as comfortable'],
    tags: ['warmup', 'cardio', 'legs'],
  },
  {
    id: 'ex_arm_circles',
    name: 'Arm Circles',
    emoji: '🔄',
    category: 'warmup',
    muscleGroups: ['shoulders'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 2,
    reps: 20,
    restBetweenSetsSec: 10,
    caloriesBurnedPerMin: 3,
    steps: [
      { step: 1, instruction: 'Stand with feet shoulder-width apart, extend arms straight out to sides', poseKey: 'arms_extended' },
      { step: 2, instruction: 'Make small forward circles with both arms simultaneously', poseKey: 'arm_circle_forward' },
      { step: 3, instruction: 'Gradually increase circle size over 10 reps', poseKey: 'arm_circle_forward' },
      { step: 4, instruction: 'Reverse direction — make backward circles', poseKey: 'arm_circle_backward' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['lose_weight', 'maintain', 'general_fitness', 'gain_muscle', 'improve_flexibility'] },
    tips: ['Keep arms straight', 'Engage shoulder muscles', 'Maintain steady breathing'],
    tags: ['warmup', 'shoulders', 'mobility'],
  },
  {
    id: 'ex_bodyweight_squats',
    name: 'Bodyweight Squats',
    emoji: '🏋️',
    category: 'strength_lower',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    difficulty: 'beginner',
    durationMin: 5,
    sets: 3,
    reps: 15,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Stand with feet shoulder-width apart, toes slightly turned out', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Push hips back and bend knees to lower down as if sitting in a chair', poseKey: 'squat_down' },
      { step: 3, instruction: 'Lower until thighs are parallel to the floor, keep chest up', poseKey: 'squat_bottom' },
      { step: 4, instruction: 'Drive through heels to stand back up, squeeze glutes at the top', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Keep knees tracking over toes', 'Don\'t let knees cave inward', 'Keep your back straight'],
    tags: ['legs', 'glutes', 'strength', 'compound'],
  },
  {
    id: 'ex_push_ups',
    name: 'Push-Ups',
    emoji: '💪',
    category: 'strength_upper',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    difficulty: 'beginner',
    durationMin: 5,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 7,
    steps: [
      { step: 1, instruction: 'Start in a high plank — hands shoulder-width apart, body in a straight line', poseKey: 'plank_high' },
      { step: 2, instruction: 'Lower your chest toward the floor by bending your elbows', poseKey: 'pushup_down' },
      { step: 3, instruction: 'Keep elbows at 45-degree angle, lower until chest nearly touches floor', poseKey: 'pushup_bottom' },
      { step: 4, instruction: 'Push back up to starting position, fully extending arms', poseKey: 'plank_high' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Keep core tight throughout', 'Don\'t sag your hips', 'Modify on knees if needed'],
    tags: ['chest', 'arms', 'strength', 'classic'],
  },
  {
    id: 'ex_plank',
    name: 'Plank Hold',
    emoji: '🧱',
    category: 'strength_core',
    muscleGroups: ['abs', 'obliques', 'shoulders'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 3,
    reps: 1,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 5,
    steps: [
      { step: 1, instruction: 'Get into forearm plank position — elbows under shoulders, body straight', poseKey: 'plank_forearm' },
      { step: 2, instruction: 'Engage your core — pull belly button toward spine', poseKey: 'plank_forearm' },
      { step: 3, instruction: 'Hold position for 30-60 seconds, keeping hips level', poseKey: 'plank_forearm' },
      { step: 4, instruction: 'Breathe steadily — don\'t hold your breath', poseKey: 'plank_forearm' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['lose_weight', 'gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Don\'t raise your hips too high', 'Keep your neck neutral', 'Start with shorter holds and build up'],
    tags: ['core', 'abs', 'isometric', 'stability'],
  },
  {
    id: 'ex_lunges',
    name: 'Forward Lunges',
    emoji: '🦿',
    category: 'strength_lower',
    muscleGroups: ['quads', 'glutes', 'hamstrings', 'calves'],
    difficulty: 'beginner',
    durationMin: 5,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Stand tall with feet hip-width apart', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Step forward with right foot, lowering hips until both knees are at 90°', poseKey: 'lunge_right' },
      { step: 3, instruction: 'Keep front knee above ankle, back knee hovering just above floor', poseKey: 'lunge_bottom' },
      { step: 4, instruction: 'Push through front heel to return to standing. Alternate legs', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Keep torso upright', 'Don\'t let front knee go past toes', 'Step far enough forward'],
    tags: ['legs', 'glutes', 'balance', 'compound'],
  },
  {
    id: 'ex_mountain_climbers',
    name: 'Mountain Climbers',
    emoji: '⛰️',
    category: 'hiit',
    muscleGroups: ['abs', 'hip_flexors', 'cardio_system', 'shoulders'],
    difficulty: 'intermediate',
    durationMin: 3,
    sets: 3,
    reps: 20,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 11,
    steps: [
      { step: 1, instruction: 'Start in high plank position — hands under shoulders, body straight', poseKey: 'plank_high' },
      { step: 2, instruction: 'Drive right knee toward chest quickly', poseKey: 'mountain_climber_right' },
      { step: 3, instruction: 'Quickly switch — extend right leg back while driving left knee forward', poseKey: 'mountain_climber_left' },
      { step: 4, instruction: 'Continue alternating at a running pace, keep hips low', poseKey: 'mountain_climber_right' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'maintain', 'general_fitness'] },
    tips: ['Keep your core tight', 'Maintain a flat back', 'Speed up gradually'],
    tags: ['hiit', 'cardio', 'core', 'full-body'],
  },
  {
    id: 'ex_burpees',
    name: 'Burpees',
    emoji: '🔥',
    category: 'hiit',
    muscleGroups: ['full_body', 'cardio_system'],
    difficulty: 'advanced',
    durationMin: 5,
    sets: 3,
    reps: 10,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 14,
    steps: [
      { step: 1, instruction: 'Stand with feet shoulder-width apart', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Drop into a squat and place hands on the floor', poseKey: 'squat_down' },
      { step: 3, instruction: 'Jump feet back into plank position', poseKey: 'plank_high' },
      { step: 4, instruction: 'Do a push-up, then jump feet forward to hands', poseKey: 'pushup_down' },
      { step: 5, instruction: 'Explode upward, jumping with arms overhead', poseKey: 'jump_arms_up' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal'], goals: ['lose_weight', 'gain_muscle', 'general_fitness'] },
    tips: ['Maintain good form even when tired', 'Land softly', 'Modify by removing the push-up if needed'],
    tags: ['hiit', 'full-body', 'cardio', 'advanced'],
  },
  {
    id: 'ex_bicycle_crunches',
    name: 'Bicycle Crunches',
    emoji: '🚴',
    category: 'strength_core',
    muscleGroups: ['abs', 'obliques'],
    difficulty: 'beginner',
    durationMin: 4,
    sets: 3,
    reps: 20,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Lie on your back, hands behind head, legs raised with knees bent 90°', poseKey: 'lying_knees_up' },
      { step: 2, instruction: 'Bring right elbow toward left knee while extending right leg', poseKey: 'bicycle_crunch_right' },
      { step: 3, instruction: 'Switch sides — left elbow to right knee, extend left leg', poseKey: 'bicycle_crunch_left' },
      { step: 4, instruction: 'Continue alternating in a pedaling motion', poseKey: 'bicycle_crunch_right' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['lose_weight', 'gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Don\'t pull on your neck', 'Control the movement', 'Full rotation of torso'],
    tags: ['core', 'abs', 'obliques'],
  },
  {
    id: 'ex_running_in_place',
    name: 'Running in Place',
    emoji: '🏃',
    category: 'cardio',
    muscleGroups: ['quads', 'calves', 'cardio_system'],
    difficulty: 'beginner',
    durationMin: 5,
    sets: 1,
    reps: 1,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 9,
    steps: [
      { step: 1, instruction: 'Stand with feet hip-width apart, arms at sides', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Begin jogging in place, lifting knees to comfortable height', poseKey: 'high_knee_right' },
      { step: 3, instruction: 'Pump arms naturally — opposite arm to leg', poseKey: 'high_knee_left' },
      { step: 4, instruction: 'Maintain steady pace for the full duration', poseKey: 'high_knee_right' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['lose_weight', 'maintain', 'general_fitness'] },
    tips: ['Stay on the balls of your feet', 'Keep a steady rhythm', 'Increase speed gradually'],
    tags: ['cardio', 'endurance', 'indoor'],
  },
  {
    id: 'ex_tricep_dips',
    name: 'Tricep Dips',
    emoji: '🪑',
    category: 'strength_upper',
    muscleGroups: ['triceps', 'shoulders', 'chest'],
    difficulty: 'intermediate',
    durationMin: 4,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Sit on edge of a sturdy chair, hands gripping the edge beside hips', poseKey: 'dip_start' },
      { step: 2, instruction: 'Slide forward off the chair, supporting weight with arms', poseKey: 'dip_hold' },
      { step: 3, instruction: 'Lower body by bending elbows to 90°, keep back close to chair', poseKey: 'dip_down' },
      { step: 4, instruction: 'Push back up to starting position by straightening arms', poseKey: 'dip_hold' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Keep elbows pointing backward', 'Don\'t shrug shoulders', 'Use a stable surface'],
    tags: ['arms', 'triceps', 'upper-body'],
  },
  {
    id: 'ex_glute_bridges',
    name: 'Glute Bridges',
    emoji: '🌉',
    category: 'strength_lower',
    muscleGroups: ['glutes', 'hamstrings', 'abs'],
    difficulty: 'beginner',
    durationMin: 4,
    sets: 3,
    reps: 15,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 5,
    steps: [
      { step: 1, instruction: 'Lie on back, knees bent, feet flat on floor hip-width apart', poseKey: 'lying_knees_bent' },
      { step: 2, instruction: 'Press through heels and squeeze glutes to lift hips toward ceiling', poseKey: 'bridge_up' },
      { step: 3, instruction: 'Hold at the top — body should form straight line from shoulders to knees', poseKey: 'bridge_top' },
      { step: 4, instruction: 'Lower hips back down slowly with control', poseKey: 'lying_knees_bent' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['gain_muscle', 'maintain', 'general_fitness', 'lose_weight'] },
    tips: ['Squeeze glutes at the top', 'Keep core engaged', 'Don\'t arch your lower back excessively'],
    tags: ['glutes', 'hamstrings', 'lower-body'],
  },
  {
    id: 'ex_wall_sit',
    name: 'Wall Sit',
    emoji: '🧱',
    category: 'strength_lower',
    muscleGroups: ['quads', 'glutes', 'calves'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 3,
    reps: 1,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 5,
    steps: [
      { step: 1, instruction: 'Stand with back flat against a wall', poseKey: 'standing_wall' },
      { step: 2, instruction: 'Slide down until thighs are parallel to the floor', poseKey: 'wall_sit' },
      { step: 3, instruction: 'Keep knees at 90° angle, back pressed firmly against wall', poseKey: 'wall_sit' },
      { step: 4, instruction: 'Hold for 30-60 seconds, breathe steadily', poseKey: 'wall_sit' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['lose_weight', 'gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Press back firmly against wall', 'Keep breathing', 'Start with shorter holds'],
    tags: ['legs', 'isometric', 'quads'],
  },
  {
    id: 'ex_superman',
    name: 'Superman Hold',
    emoji: '🦸',
    category: 'strength_core',
    muscleGroups: ['back', 'glutes', 'shoulders'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 3,
    reps: 10,
    restBetweenSetsSec: 15,
    caloriesBurnedPerMin: 4,
    steps: [
      { step: 1, instruction: 'Lie face down with arms extended overhead, legs straight', poseKey: 'lying_face_down' },
      { step: 2, instruction: 'Simultaneously lift arms, chest, and legs off the floor', poseKey: 'superman_up' },
      { step: 3, instruction: 'Hold the raised position for 2-3 seconds, squeeze back muscles', poseKey: 'superman_up' },
      { step: 4, instruction: 'Lower back down with control. Repeat', poseKey: 'lying_face_down' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness', 'improve_flexibility'] },
    tips: ['Lift with your back, not momentum', 'Keep neck neutral', 'Breathe out as you lift'],
    tags: ['back', 'core', 'posterior-chain'],
  },
  {
    id: 'ex_calf_raises',
    name: 'Calf Raises',
    emoji: '🦶',
    category: 'strength_lower',
    muscleGroups: ['calves'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 3,
    reps: 20,
    restBetweenSetsSec: 15,
    caloriesBurnedPerMin: 4,
    steps: [
      { step: 1, instruction: 'Stand with feet hip-width apart near a wall for balance', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Rise up onto the balls of your feet, lifting heels high', poseKey: 'calf_raise_up' },
      { step: 3, instruction: 'Hold at the top for 1-2 seconds, squeeze calf muscles', poseKey: 'calf_raise_up' },
      { step: 4, instruction: 'Slowly lower heels back to the ground', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Full range of motion', 'Don\'t rush', 'Use wall for balance if needed'],
    tags: ['calves', 'lower-body', 'isolation'],
  },
  {
    id: 'ex_side_plank',
    name: 'Side Plank',
    emoji: '📐',
    category: 'strength_core',
    muscleGroups: ['obliques', 'abs', 'shoulders'],
    difficulty: 'intermediate',
    durationMin: 3,
    sets: 2,
    reps: 1,
    restBetweenSetsSec: 15,
    caloriesBurnedPerMin: 5,
    steps: [
      { step: 1, instruction: 'Lie on your right side with legs stacked, right forearm on floor', poseKey: 'side_plank_setup' },
      { step: 2, instruction: 'Lift hips off the floor — body forms a straight diagonal line', poseKey: 'side_plank_hold' },
      { step: 3, instruction: 'Hold for 20-30 seconds, keeping hips elevated', poseKey: 'side_plank_hold' },
      { step: 4, instruction: 'Switch to left side and repeat', poseKey: 'side_plank_hold' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Stack feet or stagger for balance', 'Keep hips high', 'Don\'t let hips sag'],
    tags: ['core', 'obliques', 'stability'],
  },
  {
    id: 'ex_squat_jumps',
    name: 'Squat Jumps',
    emoji: '🦘',
    category: 'hiit',
    muscleGroups: ['quads', 'glutes', 'calves', 'cardio_system'],
    difficulty: 'intermediate',
    durationMin: 4,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 12,
    steps: [
      { step: 1, instruction: 'Stand with feet shoulder-width apart', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Lower into a squat — thighs parallel to floor', poseKey: 'squat_bottom' },
      { step: 3, instruction: 'Explosively jump up as high as possible, arms reaching overhead', poseKey: 'jump_arms_up' },
      { step: 4, instruction: 'Land softly back into squat position and immediately repeat', poseKey: 'squat_down' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal'], goals: ['lose_weight', 'gain_muscle', 'general_fitness'] },
    tips: ['Land softly with bent knees', 'Use your arms for momentum', 'Keep chest up'],
    tags: ['hiit', 'plyometric', 'legs', 'explosive'],
  },
  {
    id: 'ex_standing_toe_touch',
    name: 'Standing Toe Touch',
    emoji: '🤸',
    category: 'flexibility',
    muscleGroups: ['hamstrings', 'back', 'calves'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 2,
    reps: 10,
    restBetweenSetsSec: 10,
    caloriesBurnedPerMin: 3,
    steps: [
      { step: 1, instruction: 'Stand with feet together, arms at sides', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Hinge at hips, reaching down toward your toes', poseKey: 'toe_touch_down' },
      { step: 3, instruction: 'Keep legs as straight as possible, relax into the stretch', poseKey: 'toe_touch_bottom' },
      { step: 4, instruction: 'Hold for 5 seconds, then slowly roll back up', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness'] },
    tips: ['Don\'t bounce', 'Breathe into the stretch', 'Bend knees slightly if too tight'],
    tags: ['flexibility', 'hamstrings', 'stretch'],
  },
  {
    id: 'ex_cat_cow',
    name: 'Cat-Cow Stretch',
    emoji: '🐱',
    category: 'flexibility',
    muscleGroups: ['back', 'abs'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 1,
    reps: 10,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 2,
    steps: [
      { step: 1, instruction: 'Get on hands and knees — hands under shoulders, knees under hips', poseKey: 'all_fours' },
      { step: 2, instruction: 'COW: Inhale, drop belly, lift head and tailbone, arch back', poseKey: 'cow_pose' },
      { step: 3, instruction: 'CAT: Exhale, round spine upward, tuck chin and tailbone', poseKey: 'cat_pose' },
      { step: 4, instruction: 'Flow between cat and cow with your breath', poseKey: 'cow_pose' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness'] },
    tips: ['Move with your breath', 'Feel the stretch in your entire spine', 'Keep movements slow and controlled'],
    tags: ['flexibility', 'spine', 'mobility', 'yoga'],
  },
  {
    id: 'ex_downward_dog',
    name: 'Downward Dog',
    emoji: '🐕',
    category: 'yoga',
    muscleGroups: ['hamstrings', 'calves', 'shoulders', 'back'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 2,
    reps: 1,
    restBetweenSetsSec: 10,
    caloriesBurnedPerMin: 3,
    steps: [
      { step: 1, instruction: 'Start on hands and knees', poseKey: 'all_fours' },
      { step: 2, instruction: 'Lift knees off floor, push hips up and back', poseKey: 'downward_dog_transition' },
      { step: 3, instruction: 'Straighten legs, press heels toward floor, form an inverted V', poseKey: 'downward_dog' },
      { step: 4, instruction: 'Hold for 30 seconds, pressing chest toward thighs', poseKey: 'downward_dog' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['improve_flexibility', 'maintain', 'general_fitness'] },
    tips: ['Spread fingers wide', 'Bend knees slightly if hamstrings are tight', 'Relax your head and neck'],
    tags: ['yoga', 'flexibility', 'full-body'],
  },
  {
    id: 'ex_warrior_pose',
    name: 'Warrior II Pose',
    emoji: '⚔️',
    category: 'yoga',
    muscleGroups: ['quads', 'hip_flexors', 'shoulders'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 2,
    reps: 1,
    restBetweenSetsSec: 10,
    caloriesBurnedPerMin: 3,
    steps: [
      { step: 1, instruction: 'Stand with feet wide apart, about 3-4 feet', poseKey: 'wide_stance' },
      { step: 2, instruction: 'Turn right foot out 90°, left foot slightly in', poseKey: 'warrior_setup' },
      { step: 3, instruction: 'Bend right knee to 90°, extend arms out to sides at shoulder height', poseKey: 'warrior_two' },
      { step: 4, instruction: 'Gaze over right fingertips. Hold 30 seconds, then switch sides', poseKey: 'warrior_two' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness'] },
    tips: ['Keep knee over ankle', 'Sink deeper into the lunge', 'Relax your shoulders down'],
    tags: ['yoga', 'balance', 'legs', 'strength'],
  },
  {
    id: 'ex_child_pose',
    name: "Child's Pose",
    emoji: '🧒',
    category: 'cooldown',
    muscleGroups: ['back', 'hip_flexors', 'shoulders'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 1,
    reps: 1,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 2,
    steps: [
      { step: 1, instruction: 'Kneel on the floor, big toes touching, knees wide apart', poseKey: 'kneeling' },
      { step: 2, instruction: 'Sit back on your heels', poseKey: 'kneeling_sit' },
      { step: 3, instruction: 'Fold forward, extending arms out in front on the floor', poseKey: 'child_pose' },
      { step: 4, instruction: 'Rest forehead on floor, breathe deeply for 30-60 seconds', poseKey: 'child_pose' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness', 'lose_weight', 'gain_muscle'] },
    tips: ['Breathe deeply', 'Let gravity pull you deeper', 'Great rest pose between exercises'],
    tags: ['cooldown', 'stretch', 'relaxation', 'yoga'],
  },
  {
    id: 'ex_deep_breathing',
    name: 'Deep Breathing',
    emoji: '🌬️',
    category: 'cooldown',
    muscleGroups: ['abs'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 1,
    reps: 10,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 1,
    steps: [
      { step: 1, instruction: 'Sit or stand comfortably with straight posture', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Inhale slowly through nose for 4 seconds, filling belly', poseKey: 'standing_neutral' },
      { step: 3, instruction: 'Hold breath for 4 seconds', poseKey: 'standing_neutral' },
      { step: 4, instruction: 'Exhale slowly through mouth for 6 seconds. Repeat', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness', 'lose_weight', 'gain_muscle'] },
    tips: ['Focus on breath only', 'Let tension melt away', 'Practice after every workout'],
    tags: ['cooldown', 'breathing', 'recovery', 'mindfulness'],
  },
  {
    id: 'ex_diamond_pushup',
    name: 'Diamond Push-Ups',
    emoji: '💎',
    category: 'strength_upper',
    muscleGroups: ['triceps', 'chest', 'shoulders'],
    difficulty: 'advanced',
    durationMin: 5,
    sets: 3,
    reps: 10,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 8,
    steps: [
      { step: 1, instruction: 'Start in push-up position with hands close together forming a diamond shape', poseKey: 'plank_high' },
      { step: 2, instruction: 'Lower chest toward your hands, elbows close to body', poseKey: 'pushup_down' },
      { step: 3, instruction: 'Lower until chest nearly touches hands', poseKey: 'pushup_bottom' },
      { step: 4, instruction: 'Push back up. Keep core tight throughout', poseKey: 'plank_high' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal'], goals: ['gain_muscle', 'general_fitness'] },
    tips: ['Keep elbows tucked', 'Full range of motion', 'Modify on knees if needed'],
    tags: ['triceps', 'chest', 'advanced', 'upper-body'],
  },
  {
    id: 'ex_russian_twist',
    name: 'Russian Twists',
    emoji: '🌀',
    category: 'strength_core',
    muscleGroups: ['obliques', 'abs'],
    difficulty: 'intermediate',
    durationMin: 4,
    sets: 3,
    reps: 20,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Sit on floor, knees bent, feet slightly elevated', poseKey: 'seated_v' },
      { step: 2, instruction: 'Lean back slightly, clasp hands together in front of chest', poseKey: 'seated_v' },
      { step: 3, instruction: 'Rotate torso to the right, touching hands beside hip', poseKey: 'russian_twist_right' },
      { step: 4, instruction: 'Rotate to the left side. Continue alternating', poseKey: 'russian_twist_left' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness', 'lose_weight'] },
    tips: ['Keep feet off the ground for more challenge', 'Rotate from the torso not just arms', 'Control the movement'],
    tags: ['core', 'obliques', 'rotation'],
  },
  {
    id: 'ex_donkey_kicks',
    name: 'Donkey Kicks',
    emoji: '🫏',
    category: 'strength_lower',
    muscleGroups: ['glutes', 'hamstrings'],
    difficulty: 'beginner',
    durationMin: 4,
    sets: 3,
    reps: 15,
    restBetweenSetsSec: 15,
    caloriesBurnedPerMin: 5,
    steps: [
      { step: 1, instruction: 'Get on all fours — hands under shoulders, knees under hips', poseKey: 'all_fours' },
      { step: 2, instruction: 'Keep right knee bent at 90°, lift right leg behind you', poseKey: 'donkey_kick_up' },
      { step: 3, instruction: 'Push foot toward ceiling until thigh is parallel to floor', poseKey: 'donkey_kick_top' },
      { step: 4, instruction: 'Lower back down. Complete all reps then switch legs', poseKey: 'all_fours' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['gain_muscle', 'maintain', 'general_fitness', 'lose_weight'] },
    tips: ['Squeeze glutes at the top', 'Keep core stable', 'Don\'t arch your back'],
    tags: ['glutes', 'lower-body', 'isolation'],
  },
  {
    id: 'ex_hip_circles',
    name: 'Hip Circles',
    emoji: '⭕',
    category: 'warmup',
    muscleGroups: ['hip_flexors', 'glutes'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 2,
    reps: 10,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 3,
    steps: [
      { step: 1, instruction: 'Stand with feet shoulder-width apart, hands on hips', poseKey: 'hands_on_hips' },
      { step: 2, instruction: 'Make large clockwise circles with your hips', poseKey: 'hip_circle' },
      { step: 3, instruction: 'Complete 10 circles, then reverse direction', poseKey: 'hip_circle' },
      { step: 4, instruction: 'Keep upper body as still as possible', poseKey: 'hands_on_hips' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness', 'lose_weight', 'gain_muscle'] },
    tips: ['Make circles as large as comfortable', 'Loosens up hip joints', 'Great pre-workout'],
    tags: ['warmup', 'hips', 'mobility'],
  },
  {
    id: 'ex_shadow_boxing',
    name: 'Shadow Boxing',
    emoji: '🥊',
    category: 'cardio',
    muscleGroups: ['shoulders', 'chest', 'abs', 'cardio_system'],
    difficulty: 'intermediate',
    durationMin: 5,
    sets: 3,
    reps: 1,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 10,
    steps: [
      { step: 1, instruction: 'Stand in fighting stance — feet staggered, fists up by chin', poseKey: 'boxing_stance' },
      { step: 2, instruction: 'Throw jab-cross combos — extend lead hand, then rear hand', poseKey: 'boxing_jab' },
      { step: 3, instruction: 'Add hooks and uppercuts, rotate hips with each punch', poseKey: 'boxing_hook' },
      { step: 4, instruction: 'Stay light on feet, bob and weave between combos', poseKey: 'boxing_stance' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'maintain', 'general_fitness'] },
    tips: ['Keep fists up', 'Rotate hips for power', 'Stay on balls of feet'],
    tags: ['cardio', 'full-body', 'boxing', 'fun'],
  },
  {
    id: 'ex_step_ups',
    name: 'Step-Ups',
    emoji: '🪜',
    category: 'strength_lower',
    muscleGroups: ['quads', 'glutes', 'calves'],
    difficulty: 'beginner',
    durationMin: 5,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 7,
    steps: [
      { step: 1, instruction: 'Stand facing a sturdy step, bench, or stair', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Step up with right foot, driving through the heel', poseKey: 'step_up_right' },
      { step: 3, instruction: 'Bring left foot up to stand on the step', poseKey: 'standing_elevated' },
      { step: 4, instruction: 'Step down with right foot, then left. Alternate leading leg', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['lose_weight', 'gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Use a stable surface', 'Drive through the heel', 'Keep chest upright'],
    tags: ['legs', 'functional', 'balance'],
  },
  {
    id: 'ex_leg_raises',
    name: 'Lying Leg Raises',
    emoji: '🦵',
    category: 'strength_core',
    muscleGroups: ['abs', 'hip_flexors'],
    difficulty: 'intermediate',
    durationMin: 4,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 5,
    steps: [
      { step: 1, instruction: 'Lie flat on your back, legs straight, hands under lower back or at sides', poseKey: 'lying_flat' },
      { step: 2, instruction: 'Keeping legs straight, lift them toward ceiling until perpendicular to floor', poseKey: 'leg_raise_up' },
      { step: 3, instruction: 'Pause briefly at the top', poseKey: 'leg_raise_top' },
      { step: 4, instruction: 'Lower legs slowly without touching the floor. Repeat', poseKey: 'lying_flat' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness', 'lose_weight'] },
    tips: ['Keep lower back pressed into floor', 'Don\'t swing legs', 'Bend knees slightly to modify'],
    tags: ['core', 'abs', 'lower-abs'],
  },
  {
    id: 'ex_pike_pushup',
    name: 'Pike Push-Ups',
    emoji: '🔺',
    category: 'strength_upper',
    muscleGroups: ['shoulders', 'triceps'],
    difficulty: 'intermediate',
    durationMin: 4,
    sets: 3,
    reps: 10,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 7,
    steps: [
      { step: 1, instruction: 'Start in downward dog — hips high, hands and feet on floor', poseKey: 'downward_dog' },
      { step: 2, instruction: 'Bend elbows, lowering head toward floor between hands', poseKey: 'pike_pushup_down' },
      { step: 3, instruction: 'Touch head lightly to floor (or close to it)', poseKey: 'pike_pushup_bottom' },
      { step: 4, instruction: 'Push back up to starting position', poseKey: 'downward_dog' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal'], goals: ['gain_muscle', 'general_fitness'] },
    tips: ['Keep hips high', 'Targets shoulders heavily', 'Great prep for handstand push-ups'],
    tags: ['shoulders', 'upper-body', 'intermediate'],
  },
  {
    id: 'ex_flutter_kicks',
    name: 'Flutter Kicks',
    emoji: '🏊',
    category: 'strength_core',
    muscleGroups: ['abs', 'hip_flexors'],
    difficulty: 'intermediate',
    durationMin: 3,
    sets: 3,
    reps: 30,
    restBetweenSetsSec: 15,
    caloriesBurnedPerMin: 7,
    steps: [
      { step: 1, instruction: 'Lie flat on your back, hands under glutes for support', poseKey: 'lying_flat' },
      { step: 2, instruction: 'Lift both legs a few inches off the ground', poseKey: 'flutter_kick_start' },
      { step: 3, instruction: 'Alternate kicking legs up and down in a small, rapid motion', poseKey: 'flutter_kick_action' },
      { step: 4, instruction: 'Keep lower back pressed to floor throughout', poseKey: 'flutter_kick_action' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness', 'lose_weight'] },
    tips: ['Keep legs low for more challenge', 'Don\'t hold your breath', 'Engage core the entire time'],
    tags: ['core', 'abs', 'endurance'],
  },
  {
    id: 'ex_inchworm',
    name: 'Inchworm Walk',
    emoji: '🐛',
    category: 'warmup',
    muscleGroups: ['hamstrings', 'shoulders', 'abs', 'chest'],
    difficulty: 'intermediate',
    durationMin: 3,
    sets: 2,
    reps: 8,
    restBetweenSetsSec: 15,
    caloriesBurnedPerMin: 5,
    steps: [
      { step: 1, instruction: 'Stand tall, then hinge at hips and touch hands to floor', poseKey: 'toe_touch_down' },
      { step: 2, instruction: 'Walk hands forward into a high plank position', poseKey: 'plank_high' },
      { step: 3, instruction: 'Hold plank briefly, then walk feet toward hands', poseKey: 'toe_touch_bottom' },
      { step: 4, instruction: 'Stand back up. That\'s one rep', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['improve_flexibility', 'maintain', 'general_fitness'] },
    tips: ['Keep legs as straight as possible', 'Engage core during plank', 'Move slowly and deliberately'],
    tags: ['warmup', 'mobility', 'full-body'],
  },
  {
    id: 'ex_skaters',
    name: 'Skater Jumps',
    emoji: '⛸️',
    category: 'cardio',
    muscleGroups: ['quads', 'glutes', 'calves', 'cardio_system'],
    difficulty: 'intermediate',
    durationMin: 4,
    sets: 3,
    reps: 16,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 11,
    steps: [
      { step: 1, instruction: 'Stand on right foot, left foot behind you', poseKey: 'skater_right' },
      { step: 2, instruction: 'Leap to the left, landing on left foot', poseKey: 'skater_left' },
      { step: 3, instruction: 'Swing right foot behind left leg, touch floor with right hand', poseKey: 'skater_touch' },
      { step: 4, instruction: 'Leap back to the right. Continue alternating', poseKey: 'skater_right' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal'], goals: ['lose_weight', 'general_fitness', 'maintain'] },
    tips: ['Stay low', 'Land softly', 'Use arms for balance'],
    tags: ['cardio', 'agility', 'lateral-movement'],
  },
  {
    id: 'ex_neck_stretch',
    name: 'Neck Stretches',
    emoji: '🦒',
    category: 'cooldown',
    muscleGroups: ['shoulders'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 1,
    reps: 1,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 1,
    steps: [
      { step: 1, instruction: 'Stand or sit tall, shoulders relaxed', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Tilt head to the right, bringing ear toward shoulder. Hold 15 sec', poseKey: 'neck_tilt_right' },
      { step: 3, instruction: 'Tilt head to the left. Hold 15 seconds', poseKey: 'neck_tilt_left' },
      { step: 4, instruction: 'Drop chin to chest, hold. Then look up gently. Repeat cycle', poseKey: 'neck_forward' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness', 'lose_weight', 'gain_muscle'] },
    tips: ['Never force the stretch', 'Move slowly', 'Great for desk workers'],
    tags: ['cooldown', 'stretch', 'neck', 'recovery'],
  },
  {
    id: 'ex_wide_pushup',
    name: 'Wide Push-Ups',
    emoji: '🤲',
    category: 'strength_upper',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    difficulty: 'intermediate',
    durationMin: 4,
    sets: 3,
    reps: 10,
    restBetweenSetsSec: 30,
    caloriesBurnedPerMin: 7,
    steps: [
      { step: 1, instruction: 'Start in plank position with hands wider than shoulder-width', poseKey: 'plank_wide' },
      { step: 2, instruction: 'Lower chest toward floor, elbows flaring slightly outward', poseKey: 'pushup_down' },
      { step: 3, instruction: 'Lower until chest is just above the floor', poseKey: 'pushup_bottom' },
      { step: 4, instruction: 'Push back up to full extension', poseKey: 'plank_wide' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Wider hand placement targets chest more', 'Keep core tight', 'Full range of motion'],
    tags: ['chest', 'upper-body', 'push'],
  },
  {
    id: 'ex_single_leg_deadlift',
    name: 'Single Leg Deadlift',
    emoji: '🧍',
    category: 'balance',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    difficulty: 'intermediate',
    durationMin: 5,
    sets: 3,
    reps: 10,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 5,
    steps: [
      { step: 1, instruction: 'Stand on right foot, slight bend in knee', poseKey: 'single_leg_stand' },
      { step: 2, instruction: 'Hinge forward at hips, extending left leg behind you', poseKey: 'single_leg_deadlift_mid' },
      { step: 3, instruction: 'Lower torso until parallel to floor, arms hanging down', poseKey: 'single_leg_deadlift_bottom' },
      { step: 4, instruction: 'Return to standing by squeezing glutes. Switch legs', poseKey: 'single_leg_stand' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal'], goals: ['gain_muscle', 'maintain', 'general_fitness', 'improve_flexibility'] },
    tips: ['Keep hips square', 'Move slowly for balance', 'Engage core throughout'],
    tags: ['balance', 'hamstrings', 'glutes', 'unilateral'],
  },
  {
    id: 'ex_bear_crawl',
    name: 'Bear Crawl',
    emoji: '🐻',
    category: 'cardio',
    muscleGroups: ['full_body', 'shoulders', 'quads', 'abs'],
    difficulty: 'intermediate',
    durationMin: 3,
    sets: 3,
    reps: 1,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 10,
    steps: [
      { step: 1, instruction: 'Start on all fours, lift knees 1 inch off the ground', poseKey: 'bear_crawl_start' },
      { step: 2, instruction: 'Move right hand and left foot forward simultaneously', poseKey: 'bear_crawl_move' },
      { step: 3, instruction: 'Then move left hand and right foot forward', poseKey: 'bear_crawl_move' },
      { step: 4, instruction: 'Continue crawling forward for 20-30 seconds, then crawl backward', poseKey: 'bear_crawl_start' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'gain_muscle', 'general_fitness'] },
    tips: ['Keep knees low to ground', 'Move opposite hand and foot', 'Core stays tight'],
    tags: ['cardio', 'full-body', 'functional', 'animal-movement'],
  },
  {
    id: 'ex_dead_bug',
    name: 'Dead Bug',
    emoji: '🪲',
    category: 'strength_core',
    muscleGroups: ['abs', 'hip_flexors'],
    difficulty: 'beginner',
    durationMin: 4,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 15,
    caloriesBurnedPerMin: 4,
    steps: [
      { step: 1, instruction: 'Lie on back, arms extended toward ceiling, knees bent 90°', poseKey: 'dead_bug_start' },
      { step: 2, instruction: 'Lower right arm behind head while extending left leg toward floor', poseKey: 'dead_bug_extend' },
      { step: 3, instruction: 'Return to starting position', poseKey: 'dead_bug_start' },
      { step: 4, instruction: 'Repeat with left arm and right leg. Keep back flat on floor', poseKey: 'dead_bug_extend' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['maintain', 'general_fitness', 'gain_muscle'] },
    tips: ['Keep lower back pressed to floor', 'Move slowly and controlled', 'Great for beginners'],
    tags: ['core', 'stability', 'beginner-friendly'],
  },
  {
    id: 'ex_seated_forward_fold',
    name: 'Seated Forward Fold',
    emoji: '🪷',
    category: 'flexibility',
    muscleGroups: ['hamstrings', 'back'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 2,
    reps: 1,
    restBetweenSetsSec: 10,
    caloriesBurnedPerMin: 2,
    steps: [
      { step: 1, instruction: 'Sit with legs extended straight in front of you', poseKey: 'seated_legs_extended' },
      { step: 2, instruction: 'Inhale and lengthen your spine, sitting tall', poseKey: 'seated_tall' },
      { step: 3, instruction: 'Exhale and fold forward from hips, reaching for toes', poseKey: 'seated_forward_fold' },
      { step: 4, instruction: 'Hold for 30 seconds, breathing deeply into the stretch', poseKey: 'seated_forward_fold' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness'] },
    tips: ['Don\'t round your back', 'Hinge from hips', 'Bend knees if needed'],
    tags: ['flexibility', 'hamstrings', 'stretch', 'yoga'],
  },
  {
    id: 'ex_reverse_lunge',
    name: 'Reverse Lunges',
    emoji: '🔙',
    category: 'strength_lower',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    difficulty: 'beginner',
    durationMin: 5,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 25,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Stand with feet hip-width apart', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Step right foot backward, lowering into a lunge', poseKey: 'reverse_lunge_right' },
      { step: 3, instruction: 'Both knees at 90°, back knee hovering above floor', poseKey: 'lunge_bottom' },
      { step: 4, instruction: 'Push through front heel to return to standing. Alternate legs', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Easier on knees than forward lunges', 'Keep torso upright', 'Control the descent'],
    tags: ['legs', 'glutes', 'compound'],
  },
  {
    id: 'ex_hip_thrust',
    name: 'Hip Thrusts',
    emoji: '🍑',
    category: 'strength_lower',
    muscleGroups: ['glutes', 'hamstrings'],
    difficulty: 'intermediate',
    durationMin: 5,
    sets: 3,
    reps: 15,
    restBetweenSetsSec: 25,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Sit on floor with upper back against a bench or couch edge', poseKey: 'hip_thrust_start' },
      { step: 2, instruction: 'Plant feet flat, hip-width apart, knees bent', poseKey: 'hip_thrust_start' },
      { step: 3, instruction: 'Drive hips upward until body forms straight line from shoulders to knees', poseKey: 'hip_thrust_top' },
      { step: 4, instruction: 'Squeeze glutes hard at top, then lower slowly', poseKey: 'hip_thrust_start' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Squeeze glutes at top', 'Keep chin tucked', 'Full range of motion'],
    tags: ['glutes', 'lower-body', 'strength'],
  },
  {
    id: 'ex_shoulder_tap',
    name: 'Plank Shoulder Taps',
    emoji: '👋',
    category: 'strength_core',
    muscleGroups: ['abs', 'shoulders', 'chest'],
    difficulty: 'intermediate',
    durationMin: 3,
    sets: 3,
    reps: 16,
    restBetweenSetsSec: 20,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Start in high plank position, feet slightly wider than hip-width', poseKey: 'plank_high' },
      { step: 2, instruction: 'Lift right hand and tap left shoulder', poseKey: 'shoulder_tap_right' },
      { step: 3, instruction: 'Return hand to floor, then lift left hand and tap right shoulder', poseKey: 'shoulder_tap_left' },
      { step: 4, instruction: 'Alternate sides, keeping hips as still as possible', poseKey: 'plank_high' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Minimize hip rotation', 'Widen feet for stability', 'Engage core throughout'],
    tags: ['core', 'stability', 'anti-rotation'],
  },
  {
    id: 'ex_quad_stretch',
    name: 'Standing Quad Stretch',
    emoji: '🦵',
    category: 'cooldown',
    muscleGroups: ['quads', 'hip_flexors'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 1,
    reps: 1,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 1,
    steps: [
      { step: 1, instruction: 'Stand on left foot, grab right ankle behind you with right hand', poseKey: 'quad_stretch_right' },
      { step: 2, instruction: 'Pull heel toward glute, keep knees together', poseKey: 'quad_stretch_hold' },
      { step: 3, instruction: 'Hold for 20-30 seconds, use wall for balance if needed', poseKey: 'quad_stretch_hold' },
      { step: 4, instruction: 'Switch to left leg', poseKey: 'quad_stretch_left' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness', 'lose_weight', 'gain_muscle'] },
    tips: ['Keep standing knee slightly bent', 'Don\'t arch your back', 'Hold for at least 20 seconds'],
    tags: ['cooldown', 'stretch', 'quads'],
  },
  {
    id: 'ex_tree_pose',
    name: 'Tree Pose',
    emoji: '🌳',
    category: 'balance',
    muscleGroups: ['quads', 'calves', 'abs'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 2,
    reps: 1,
    restBetweenSetsSec: 10,
    caloriesBurnedPerMin: 3,
    steps: [
      { step: 1, instruction: 'Stand on left foot, find a focus point ahead', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Place right foot on inner left thigh or calf (not on knee)', poseKey: 'tree_pose' },
      { step: 3, instruction: 'Bring hands to prayer position at chest, or extend overhead', poseKey: 'tree_pose_arms_up' },
      { step: 4, instruction: 'Hold 30 seconds, then switch sides', poseKey: 'tree_pose' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness'] },
    tips: ['Focus gaze on fixed point', 'Start with foot on calf if needed', 'Engage your core'],
    tags: ['balance', 'yoga', 'stability'],
  },
  {
    id: 'ex_fire_hydrant',
    name: 'Fire Hydrants',
    emoji: '🚒',
    category: 'strength_lower',
    muscleGroups: ['glutes', 'hip_flexors'],
    difficulty: 'beginner',
    durationMin: 4,
    sets: 3,
    reps: 15,
    restBetweenSetsSec: 15,
    caloriesBurnedPerMin: 4,
    steps: [
      { step: 1, instruction: 'Get on all fours — hands under shoulders, knees under hips', poseKey: 'all_fours' },
      { step: 2, instruction: 'Keep right knee bent at 90°, lift it out to the side', poseKey: 'fire_hydrant_up' },
      { step: 3, instruction: 'Raise until thigh is parallel to floor, hold briefly', poseKey: 'fire_hydrant_top' },
      { step: 4, instruction: 'Lower back to start. Complete all reps then switch legs', poseKey: 'all_fours' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['gain_muscle', 'maintain', 'general_fitness', 'lose_weight'] },
    tips: ['Don\'t rotate hips', 'Keep core stable', 'Control the movement'],
    tags: ['glutes', 'hips', 'isolation'],
  },
  {
    id: 'ex_side_lunge',
    name: 'Side Lunges',
    emoji: '↔️',
    category: 'strength_lower',
    muscleGroups: ['quads', 'glutes', 'hip_flexors'],
    difficulty: 'intermediate',
    durationMin: 5,
    sets: 3,
    reps: 12,
    restBetweenSetsSec: 25,
    caloriesBurnedPerMin: 6,
    steps: [
      { step: 1, instruction: 'Stand with feet together', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Step right foot wide to the right, bending right knee', poseKey: 'side_lunge_right' },
      { step: 3, instruction: 'Push hips back, keep left leg straight, chest up', poseKey: 'side_lunge_bottom' },
      { step: 4, instruction: 'Push through right foot to return. Alternate sides', poseKey: 'standing_neutral' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'gain_muscle', 'maintain', 'general_fitness'] },
    tips: ['Keep both feet pointing forward', 'Chest stays upright', 'Go as deep as comfortable'],
    tags: ['legs', 'lateral', 'compound'],
  },
  {
    id: 'ex_marching_in_place',
    name: 'Marching in Place',
    emoji: '🚶',
    category: 'warmup',
    muscleGroups: ['quads', 'hip_flexors', 'cardio_system'],
    difficulty: 'beginner',
    durationMin: 3,
    sets: 1,
    reps: 1,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 4,
    steps: [
      { step: 1, instruction: 'Stand tall with feet hip-width apart', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Lift right knee to hip height while swinging left arm forward', poseKey: 'march_right' },
      { step: 3, instruction: 'Lower and lift left knee while swinging right arm forward', poseKey: 'march_left' },
      { step: 4, instruction: 'Continue at a brisk pace for the full duration', poseKey: 'march_right' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['lose_weight', 'maintain', 'general_fitness'] },
    tips: ['Lift knees high', 'Swing arms naturally', 'Good low-impact warmup'],
    tags: ['warmup', 'low-impact', 'cardio'],
  },
  {
    id: 'ex_butt_kicks',
    name: 'Butt Kicks',
    emoji: '🦶',
    category: 'warmup',
    muscleGroups: ['hamstrings', 'quads', 'cardio_system'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 1,
    reps: 30,
    restBetweenSetsSec: 0,
    caloriesBurnedPerMin: 8,
    steps: [
      { step: 1, instruction: 'Stand with feet hip-width apart', poseKey: 'standing_neutral' },
      { step: 2, instruction: 'Jog in place, kicking heels up toward your glutes', poseKey: 'butt_kick_right' },
      { step: 3, instruction: 'Alternate legs rapidly, pumping arms', poseKey: 'butt_kick_left' },
      { step: 4, instruction: 'Try to touch heels to glutes each rep', poseKey: 'butt_kick_right' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight'], goals: ['lose_weight', 'maintain', 'general_fitness'] },
    tips: ['Stay on balls of feet', 'Keep a fast pace', 'Great hamstring warmup'],
    tags: ['warmup', 'cardio', 'hamstrings'],
  },
  {
    id: 'ex_cobra_stretch',
    name: 'Cobra Stretch',
    emoji: '🐍',
    category: 'flexibility',
    muscleGroups: ['abs', 'back', 'chest'],
    difficulty: 'beginner',
    durationMin: 2,
    sets: 2,
    reps: 1,
    restBetweenSetsSec: 10,
    caloriesBurnedPerMin: 2,
    steps: [
      { step: 1, instruction: 'Lie face down, hands under shoulders, legs straight', poseKey: 'lying_face_down' },
      { step: 2, instruction: 'Press hands into floor, lifting chest up while keeping hips down', poseKey: 'cobra_up' },
      { step: 3, instruction: 'Straighten arms as much as comfortable, look slightly upward', poseKey: 'cobra_full' },
      { step: 4, instruction: 'Hold for 20-30 seconds, then lower slowly', poseKey: 'lying_face_down' },
    ],
    suitableFor: { gender: ['male', 'female'], bmiCategories: ['underweight', 'normal', 'overweight', 'obese'], goals: ['improve_flexibility', 'maintain', 'general_fitness'] },
    tips: ['Keep shoulders down and back', 'Don\'t overextend', 'Breathe deeply'],
    tags: ['flexibility', 'back', 'stretch', 'yoga'],
  },
];
